# Generated by Django 5.0.12 on 2026-07-02 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100, verbose_name='Event Type')),
                ('property_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('lease_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='events_doma_event_t_75f145_idx')],
            },
        ),
    ]
