# Generated by Django 5.0.12 on 2026-07-02 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0007_alter_lease_lease_type'),
        ('properties', '0007_area_area_area_belongs_to_group_xor_property'),
        ('users', '0005_alter_user_managers_remove_user_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ledger_attachments/%Y/%m/', verbose_name='File')),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='Label')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('RENT_CHARGE', 'Rent Charge'), ('UTILITY_CHARGE', 'Utility Charge'), ('DEPOSIT_CHARGE', 'Deposit Charge'), ('FEE_CHARGE', 'Fee Charge'), ('OTHER_CHARGE', 'Other Charge'), ('PAYMENT', 'Payment Received'), ('CREDIT', 'Credit / Discount'), ('EXPENSE', 'Expense'), ('DEPOSIT_RETURN', 'Deposit Returned'), ('REVERSAL', 'Reversal (void)')], db_index=True, max_length=20, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive; the entry type carries the direction.', max_digits=12, verbose_name='Amount')),
                ('due_date', models.DateField(blank=True, db_index=True, help_text='Charges only.', null=True, verbose_name='Due Date')),
                ('effective_date', models.DateField(db_index=True, help_text='Service period start / payment date / date incurred.', verbose_name='Effective Date')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('payment_method', models.CharField(blank=True, choices=[('ETRANSFER', 'e-Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='', help_text='PAYMENT / DEPOSIT_RETURN entries.', max_length=12, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Reference #')),
                ('category', models.CharField(blank=True, choices=[('MAINTENANCE', 'Maintenance / Repairs'), ('UTILITIES', 'Utilities (landlord-paid)'), ('INSURANCE', 'Insurance'), ('PROPERTY_TAX', 'Property Tax'), ('MORTGAGE', 'Mortgage / Financing'), ('STRATA', 'Strata / HOA Fees'), ('MANAGEMENT', 'Management / Professional Fees'), ('SUPPLIES', 'Supplies / Furnishings'), ('ADVERTISING', 'Advertising / Listing'), ('OTHER', 'Other')], default='', max_length=20, verbose_name='Expense Category')),
                ('vendor', models.CharField(blank=True, max_length=150, verbose_name='Vendor / Payee')),
                ('idempotency_key', models.CharField(blank=True, help_text='Natural key for generated entries; client-generated UUID for API writes. Duplicate submissions are rejected by the database.', max_length=180, null=True, unique=True, verbose_name='Idempotency Key')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='users.landlordprofile')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='leases.lease')),
                ('property', models.ForeignKey(blank=True, help_text='The ledger this entry belongs to. NULL = portfolio-wide (e.g. accountant fees).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='properties.property')),
                ('reverses', models.OneToOneField(blank=True, help_text='For REVERSAL: the entry this voids. OneToOne — an entry can be voided exactly once.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='ledger.ledgerentry')),
                ('settles', models.ForeignKey(blank=True, help_text='For PAYMENT/CREDIT: the charge this settles.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='ledger.ledgerentry')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='users.tenantprofile')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
