# Generated by Django 5.0.12 on 2026-07-02 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='Expense/charge tied to a maintenance job, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='maintenance.workorder'),
        ),
        migrations.AddField(
            model_name='ledgerattachment',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ledger.ledgerentry'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['landlord', 'entry_type', 'effective_date'], name='ledger_ledg_landlor_ce0587_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['lease', 'entry_type', 'due_date'], name='ledger_ledg_lease_i_e1afed_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='ledger_amount_positive'),
        ),
    ]
