# Generated by Django 5.0.12 on 2026-07-10 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_initial'),
        ('users', '0005_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Charges: who owes it — NULL with a lease set means the whole household owes it jointly. Payments: who paid.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='users.tenantprofile'),
        ),
    ]
