# Generated by Django 5.0.12 on 2026-07-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_ledgerentry_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='paid_on',
            field=models.DateField(blank=True, help_text='EXPENSE entries only. NULL = recorded, but not yet taken from the bank. Set it when the payment actually clears.', null=True, verbose_name='Left My Account On'),
        ),
    ]
