# Generated by Django 5.0.12 on 2026-07-20 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_expense_paid_on'),
        ('properties', '0010_propertyholding_property_holding'),
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyBankBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='Operating', max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('as_of', models.DateField()),
                ('updated_via', models.CharField(choices=[('UI', 'Entered in the app'), ('CHAT', 'Entered via RAMA')], default='UI', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holding', models.ForeignKey(blank=True, help_text='Null = portfolio-wide balance (no per-house breakdown yet).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_balances', to='properties.propertyholding')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_balances', to='users.landlordprofile')),
            ],
            options={
                'verbose_name': 'Bank Balance',
                'verbose_name_plural': 'Bank Balances',
                'ordering': ['landlord', 'holding__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='propertybankbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('holding__isnull', False)), fields=('landlord', 'holding'), name='ledger_bank_balance_one_per_holding'),
        ),
        migrations.AddConstraint(
            model_name='propertybankbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('holding__isnull', True)), fields=('landlord',), name='ledger_bank_balance_one_portfolio_wide'),
        ),
    ]
