# Generated by Django 5.0.12 on 2026-07-20 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0013_lease_house_rules_lease_occupants_and_more'),
        ('ledger', '0005_propertybankbalance_and_more'),
        ('properties', '0010_propertyholding_property_holding'),
        ('users', '0006_alter_user_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='ledger_imports/%Y/%m/')),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('column_map', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft — still editable'), ('COMMITTED', 'Committed'), ('DISCARDED', 'Discarded')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='users.landlordprofile')),
            ],
            options={
                'verbose_name': 'Import Batch',
                'verbose_name_plural': 'Import Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StagedLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('entry_type', models.CharField(blank=True, choices=[('RENT_CHARGE', 'Rent Charge'), ('UTILITY_CHARGE', 'Utility Charge'), ('DEPOSIT_CHARGE', 'Deposit Charge'), ('FEE_CHARGE', 'Fee Charge'), ('OTHER_CHARGE', 'Other Charge'), ('PAYMENT', 'Payment Received'), ('CREDIT', 'Credit / Discount'), ('EXPENSE', 'Expense'), ('DEPOSIT_RETURN', 'Deposit Returned'), ('REVERSAL', 'Reversal (void)')], default='', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=30)),
                ('vendor', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('payment_method', models.CharField(blank=True, default='', max_length=20)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ledger.importbatch')),
                ('committed_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledger.ledgerentry')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leases.lease')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
                ('settles_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledger.stagedledgerentry')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tenantprofile')),
            ],
            options={
                'verbose_name': 'Staged Ledger Entry',
                'verbose_name_plural': 'Staged Ledger Entries',
                'ordering': ['batch', 'row_number'],
            },
        ),
    ]
