# Generated by Django 5.0.12 on 2026-07-27 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_ledgerentry_holding'),
        ('properties', '0015_propertyarea_is_seeded_default'),
        ('rama', '0016_treasurer_role'),
        ('users', '0009_remove_landlordteammember_uniq_team_owner_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('land_transfer_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closing_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('capital_improvements_to_date', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('heated_area_sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('heating_type', models.CharField(blank=True, default='', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='properties.propertyholding')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_financials', to='users.landlordprofile')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rama.ramadocument')),
            ],
            options={
                'verbose_name': 'holding financials',
                'verbose_name_plural': 'holding financials',
            },
        ),
        migrations.CreateModel(
            name='HoldingValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('basis', models.CharField(choices=[('BC_ASSESSMENT', 'BC Assessment'), ('REALTOR_CMA', 'Realtor comparative market analysis'), ('APPRAISAL', 'Professional appraisal'), ('LANDLORD_ESTIMATE', "Landlord's own estimate"), ('AUTOMATED', 'Automated estimate')], max_length=20)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('source_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='properties.propertyholding')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_valuations', to='users.landlordprofile')),
            ],
            options={
                'ordering': ['-as_of'],
            },
        ),
        migrations.CreateModel(
            name='HoldingMortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.CharField(blank=True, default='', max_length=120)),
                ('original_principal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('current_principal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('current_principal_as_of', models.DateField(blank=True, null=True)),
                ('rate_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('rate_type', models.CharField(blank=True, choices=[('FIXED', 'Fixed'), ('VARIABLE', 'Variable')], default='', max_length=10)),
                ('amortization_months', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_frequency', models.CharField(blank=True, default='', max_length=12)),
                ('term_start', models.DateField(blank=True, null=True)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCHARGED', 'Discharged'), ('SUPERSEDED', 'Superseded by a renewal')], db_index=True, default='ACTIVE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgages', to='properties.propertyholding')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_mortgages', to='users.landlordprofile')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rama.ramadocument')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledger.holdingmortgage')),
            ],
            options={
                'ordering': ['-term_start', '-created_at'],
                'indexes': [models.Index(fields=['landlord', 'status', 'term_end'], name='ledger_hold_landlor_5eff09_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='holdingmortgage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('holding',), name='holding_mortgage_single_active'),
        ),
        migrations.AddIndex(
            model_name='holdingvaluation',
            index=models.Index(fields=['landlord', 'holding', '-as_of'], name='ledger_hold_landlor_326f32_idx'),
        ),
        migrations.AddConstraint(
            model_name='holdingvaluation',
            constraint=models.UniqueConstraint(fields=('holding', 'as_of', 'basis'), name='holding_valuation_unique_per_basis_date'),
        ),
    ]
