# Generated by Django 5.0.12 on 2026-07-02 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0007_alter_lease_lease_type'),
        ('properties', '0007_area_area_area_belongs_to_group_xor_property'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('TENANT', 'Tenant Reported'), ('LANDLORD', 'Landlord Initiated'), ('ROUTINE', 'Routine / Preventive')], default='TENANT', max_length=10, verbose_name='Origin')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('HEATING_COOLING', 'Heating / Cooling'), ('APPLIANCE', 'Appliance'), ('STRUCTURAL', 'Structural / Doors / Windows'), ('PEST', 'Pest Control'), ('SAFETY', 'Safety (locks, detectors)'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Category')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency')], default='MEDIUM', max_length=10, verbose_name='Priority')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=15, verbose_name='Status')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Scheduled Date')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Completed Date')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Actual Cost')),
                ('contractor_name', models.CharField(blank=True, max_length=150, verbose_name='Contractor')),
                ('contractor_phone', models.CharField(blank=True, max_length=30, verbose_name='Contractor Phone')),
                ('sla_due_at', models.DateTimeField(blank=True, null=True, verbose_name='SLA Deadline')),
                ('first_actioned_at', models.DateTimeField(blank=True, null=True)),
                ('sla_breach_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, help_text='Which space the issue is in. Blank = the room/unit itself.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='properties.area')),
                ('lease', models.ForeignKey(blank=True, help_text='Lease active when the issue was reported, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='leases.lease')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='properties.property')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='maintenance/%Y/%m/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
