# Generated by Django 5.0.12 on 2026-07-12 01:08

import rentium.core.phone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='contractor_phone',
            field=rentium.core.phone.PhoneField(blank=True, default='', max_length=20, verbose_name='Contractor Phone'),
        ),
    ]
