# Generated by Django 5.0.12 on 2026-07-26 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_workorder_area'),
        ('properties', '0015_propertyarea_is_seeded_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='For faults in shared space rather than one listing.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='properties.propertyunit'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='properties.property'),
        ),
    ]
