# Generated by Django 5.0.12 on 2026-07-26 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_workorder_unit_alter_workorder_property'),
        ('users', '0009_remove_landlordteammember_uniq_team_owner_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='responsible_tenant',
            field=models.ForeignKey(blank=True, help_text="The tenant who caused this, if it wasn't wear and tear.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributed_work_orders', to='users.tenantprofile'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='tenant_chargeable',
            field=models.BooleanField(default=False, help_text='The cost is claimed from the responsible tenant. This raises a CLAIM they owe — it never deducts from a deposit by itself.', verbose_name='Chargeable to tenant'),
        ),
    ]
