# Generated by Django 5.0.12 on 2026-07-03 03:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0008_occupancy'),
        ('properties', '0007_area_area_area_belongs_to_group_xor_property'),
        ('users', '0005_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('CUSTOM', 'Custom'), ('INSPECTION', 'Inspection'), ('REMINDER', 'Reminder'), ('MOVE', 'Move-in / Move-out')], default='CUSTOM', max_length=12)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_events', to='leases.lease')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_events', to='users.landlordprofile')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_events', to='properties.property')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
