# Generated by Django 5.0.12 on 2025-03-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_remove_user_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('LANDLORD', 'Landlord'), ('TENANT', 'Tenant')], default='TENANT', max_length=10, verbose_name='User Type'),
        ),
    ]
