# Generated by Django 5.0.12 on 2025-03-22 08:38

import rentium.users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_user_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', rentium.users.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='province',
            field=models.CharField(max_length=100, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('LANDLORD', 'Landlord'), ('TENANT', 'Tenant')], max_length=8, null=True, verbose_name='User Type'),
        ),
    ]
