# Generated by Django 5.0.12 on 2026-07-12 01:08

import rentium.core.phone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=rentium.core.phone.PhoneField(blank=True, default='', max_length=20, verbose_name='Phone Number'),
        ),
    ]
