# Generated by Django 5.0.12 on 2026-07-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='timezone',
            field=models.CharField(default='America/Vancouver', help_text='IANA timezone name, e.g. America/Vancouver.', max_length=64, verbose_name='Timezone'),
        ),
    ]
