# Generated by Django 5.0.12 on 2026-07-22 02:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_landlordprofile_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invited_email', models.EmailField(blank=True, default='', max_length=254)),
                ('invited_name', models.CharField(blank=True, default='', max_length=150)),
                ('role', models.CharField(choices=[('MANAGER', 'Manager (full access)')], default='MANAGER', max_length=20)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, help_text='Set once the invited person has an account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_landlord_memberships', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='users.landlordprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='landlordteammember',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', False)), fields=('owner', 'member'), name='uniq_team_owner_member'),
        ),
    ]
