# Generated by Django 5.0.12 on 2026-07-22 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_propertyholding_property_holding'),
        ('users', '0008_landlordteammember_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='landlordteammember',
            name='uniq_team_owner_member',
        ),
        migrations.AddField(
            model_name='landlordteammember',
            name='scope_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_landlord_grants', to='properties.propertygroup'),
        ),
        migrations.AddField(
            model_name='landlordteammember',
            name='scope_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_landlord_grants', to='properties.property'),
        ),
        migrations.AddConstraint(
            model_name='landlordteammember',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', False)), fields=('owner', 'member', 'scope_property', 'scope_group'), name='uniq_team_owner_member_scope'),
        ),
    ]
