# Generated by Django 5.0.12 on 2025-04-09 19:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0006_alter_propertyarea_unique_together_and_more'),
        ('users', '0005_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lease_type', models.CharField(choices=[('BC_ROOMMATE', 'BC TRAC Roommate Agreement'), ('BC_RESIDENTIAL', 'BC Residential Tenancy (RTB-1)'), ('SK_ROOMMATE', 'Saskatchewan Roommate Agreement'), ('SK_RESIDENTIAL', 'Saskatchewan Residential Tenancy'), ('GENERIC_ROOMMATE', 'Standard Roommate Agreement'), ('GENERIC_RESIDENTIAL', 'Standard Residential Agreement')], max_length=25, verbose_name='Lease Type')),
                ('lease_number', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Lease Number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Signatures'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('RENEWED', 'Renewed')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Blank for month-to-month', null=True, verbose_name='End Date')),
                ('is_month_to_month', models.BooleanField(default=False, verbose_name='Month-to-Month')),
                ('move_in_date', models.DateField(blank=True, null=True, verbose_name='Move-in Date')),
                ('move_out_date', models.DateField(blank=True, null=True, verbose_name='Move-out Date')),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Security Deposit')),
                ('pet_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pet Deposit')),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=0, help_text='Overall fee for complete units; individual fees are in LeaseTenant for roommates', max_digits=10, verbose_name='Cleaning Fee (Overall Lease)')),
                ('pets_allowed', models.BooleanField(default=False, verbose_name='Pets Allowed')),
                ('smoking_allowed', models.BooleanField(default=False, verbose_name='Smoking Allowed')),
                ('utilities_included', models.JSONField(blank=True, default=dict, help_text="JSON format, e.g., {'electricity': true, 'water': true, 'internet': false}", verbose_name='Utilities Included')),
                ('special_terms', models.TextField(blank=True, verbose_name='Special Terms')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='lease_documents/%Y/%m/', verbose_name='Main Agreement Document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, help_text='Link to a group for shared accommodation agreements covering multiple rooms', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_leases', to='properties.propertygroup')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landlord_leases', to='users.landlordprofile')),
                ('previous_lease', models.ForeignKey(blank=True, help_text='Link to the lease this one renewed/replaced', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_leases', to='leases.lease')),
                ('property', models.ForeignKey(blank=True, help_text='Link to a specific property (Room or Complete Unit)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.property')),
            ],
            options={
                'verbose_name': 'Lease',
                'verbose_name_plural': 'Leases',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('document', models.FileField(upload_to='lease_documents/%Y/%m/additional/', verbose_name='Document File')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_signed', models.BooleanField(default=False, help_text='Indicates if this specific document requires/has signatures', verbose_name='Is Signed')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='leases.lease')),
            ],
            options={
                'verbose_name': 'Lease Document',
                'verbose_name_plural': 'Lease Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('RENT', 'Rent Payment'), ('SECURITY_DEPOSIT', 'Security Deposit'), ('PET_DEPOSIT', 'Pet Deposit'), ('CLEANING_FEE', 'Cleaning Fee'), ('LATE_FEE', 'Late Fee'), ('UTILITY', 'Utility Payment'), ('MAINTENANCE', 'Maintenance Fee/Chargeback'), ('OTHER', 'Other')], max_length=20, verbose_name='Payment Type')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Due')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount Paid')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('payment_date', models.DateField(blank=True, help_text='Date payment was completed', null=True, verbose_name='Payment Date')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIALLY_PAID', 'Partially Paid'), ('OVERDUE', 'Overdue'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('ETRANSFER', 'E-Transfer'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('OTHER', 'Other'), ('NA', 'N/A')], default='NA', max_length=20, null=True, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, help_text='Optional reference for tracking (e.g., cheque number, transaction ID)', max_length=100, verbose_name='Reference/Transaction ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/', verbose_name='Receipt File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='leases.lease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='users.tenantprofile')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_date', models.DateField(help_text='Date the reminder should be sent', verbose_name='Reminder Date')),
                ('message_template', models.TextField(blank=True, help_text='Optional custom message, otherwise default used', verbose_name='Message Template')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Is Sent')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Sent')),
                ('send_method', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('APP', 'In-App')], default='EMAIL', max_length=10, verbose_name='Send Method')),
                ('error_message', models.TextField(blank=True, help_text='Records any error during sending', verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='leases.payment')),
            ],
            options={
                'verbose_name': 'Payment Reminder',
                'verbose_name_plural': 'Payment Reminders',
                'ordering': ['reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaseTenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Individual Monthly Rent')),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=0, help_text='Cleaning fee charged specifically to this tenant (for roommate leases)', max_digits=10, verbose_name='Individual Cleaning Fee')),
                ('cleaning_fee_paid', models.BooleanField(default=False, verbose_name='Cleaning Fee Paid')),
                ('is_primary_tenant', models.BooleanField(default=False, help_text='Is this the primary contact for communications regarding the lease?', verbose_name='Primary Tenant')),
                ('has_signed', models.BooleanField(default=False, verbose_name='Has Signed Agreement')),
                ('signed_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Signed')),
                ('individual_start_date', models.DateField(blank=True, help_text="Tenant's specific start date if different from lease.start_date", null=True, verbose_name='Individual Start Date')),
                ('individual_end_date', models.DateField(blank=True, help_text="Tenant's specific end date if different from lease.end_date", null=True, verbose_name='Individual End Date')),
                ('tenant_notes', models.TextField(blank=True, verbose_name='Notes specific to this tenant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_tenants', to='leases.lease')),
                ('room', models.ForeignKey(blank=True, help_text='Specific room assignment within a group lease (Roommate Agreements only)', limit_choices_to={'property_category': 'ROOM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_tenants', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_leases', to='users.tenantprofile')),
            ],
            options={
                'verbose_name': 'Lease Tenant',
                'verbose_name_plural': 'Lease Tenants',
                'ordering': ['lease', 'tenant__user__name'],
                'unique_together': {('lease', 'tenant')},
            },
        ),
    ]
