# Generated by Django 5.0.12 on 2025-04-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='utilities_included',
        ),
        migrations.AddField(
            model_name='lease',
            name='bills_included',
            field=models.JSONField(blank=True, default=dict, help_text="JSON format for included bills with customizable provider names. Example: {'electricity': {'included': true, 'provider': 'BC Hydro'}, 'internet': {'included': false, 'provider': 'Telus'}, ...}", verbose_name='Bills Included'),
        ),
    ]
