# Generated by Django 5.0.12 on 2025-04-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_remove_lease_utilities_included_lease_bills_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='utility_period_end',
            field=models.DateField(blank=True, null=True, verbose_name='Utility Period End'),
        ),
        migrations.AddField(
            model_name='payment',
            name='utility_period_start',
            field=models.DateField(blank=True, null=True, verbose_name='Utility Period Start'),
        ),
        migrations.AddField(
            model_name='payment',
            name='utility_provider',
            field=models.CharField(blank=True, help_text='Provider name for utility payments', max_length=100, verbose_name='Utility Provider'),
        ),
        migrations.AddField(
            model_name='payment',
            name='utility_type',
            field=models.CharField(blank=True, help_text='If this is a utility payment, specify which utility (e.g., electricity, water)', max_length=50, verbose_name='Utility Type'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='bills_included',
            field=models.JSONField(blank=True, default=dict, help_text="JSON format for utilities with provider names, tenant responsibility, and distribution. Example: {'electricity': {'included': false, 'provider': 'BC Hydro', 'tenant_responsibility': {'type': 'percentage', 'value': 75, 'distribution': 'equal'}}}", verbose_name='Bills Included'),
        ),
    ]
