# Generated by Django 5.0.12 on 2026-07-01 01:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_payment_utility_period_end_and_more'),
        ('users', '0005_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leasetenant',
            options={'ordering': ['lease', 'invited_email'], 'verbose_name': 'Lease Tenant', 'verbose_name_plural': 'Lease Tenants'},
        ),
        migrations.AlterUniqueTogether(
            name='leasetenant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lease',
            name='common_space_shared_with',
            field=models.JSONField(blank=True, default=list, help_text="Only relevant for ROOMMATE-type leases. Subset of ['ROOMMATES', 'LANDLORD', 'LANDLORD_RELATIVES'] describing who else may use the shared common spaces. Rendered into the lease document's shared-space clause.", verbose_name='Common Space Shared With'),
        ),
        migrations.AddField(
            model_name='lease',
            name='fixed_term_end_reason',
            field=models.TextField(blank=True, help_text='Required only if this lease ends with a mandatory vacate clause (RTA s.13.1 or sublease)', verbose_name='Reason Tenant Must Vacate'),
        ),
        migrations.AddField(
            model_name='lease',
            name='fixed_term_end_regulation_section',
            field=models.CharField(blank=True, max_length=20, verbose_name='Residential Tenancy Regulation Section'),
        ),
        migrations.AddField(
            model_name='lease',
            name='landlord_daytime_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Landlord Daytime Phone'),
        ),
        migrations.AddField(
            model_name='lease',
            name='landlord_fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='Landlord Fax'),
        ),
        migrations.AddField(
            model_name='lease',
            name='landlord_other_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Landlord Other Phone'),
        ),
        migrations.AddField(
            model_name='lease',
            name='landlord_service_address',
            field=models.CharField(blank=True, help_text='Defaults to the rental unit/property address if left blank', max_length=255, verbose_name='Landlord Address for Service'),
        ),
        migrations.AddField(
            model_name='lease',
            name='landlord_service_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Landlord Email for Service'),
        ),
        migrations.AddField(
            model_name='lease',
            name='landlord_signed',
            field=models.BooleanField(default=False, verbose_name='Landlord Signed'),
        ),
        migrations.AddField(
            model_name='lease',
            name='landlord_signed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Landlord Signed'),
        ),
        migrations.AddField(
            model_name='leasetenant',
            name='invite_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Invite Accepted At'),
        ),
        migrations.AddField(
            model_name='leasetenant',
            name='invite_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Invite Sent At'),
        ),
        migrations.AddField(
            model_name='leasetenant',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Invite Token'),
        ),
        migrations.AddField(
            model_name='leasetenant',
            name='invited_email',
            field=models.EmailField(blank=True, help_text='Email the landlord entered when creating this LeaseTenant slot.', max_length=254, verbose_name='Invited Email'),
        ),
        migrations.AddField(
            model_name='leasetenant',
            name='invited_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Invited Phone'),
        ),
        migrations.AlterField(
            model_name='leasetenant',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Set once the invited person has a linked account. Null while invite is pending.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_leases', to='users.tenantprofile'),
        ),
        migrations.CreateModel(
            name='RentAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('PRORATION', 'First Month Proration'), ('DISCOUNT', 'Negotiated Discount'), ('INCREASE', 'Rent Increase'), ('OTHER', 'Other')], max_length=20, verbose_name='Adjustment Type')),
                ('calculation_method', models.CharField(choices=[('EXACT_NIGHTLY', 'Exact per-night calculation'), ('FLAT_AMOUNT', 'Flat amount'), ('PERCENTAGE', 'Percentage')], max_length=20, verbose_name='Calculation Method')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Dollar amount off/on for FLAT_AMOUNT, or the % value for PERCENTAGE (ignored for EXACT_NIGHTLY, use nights fields)', max_digits=10, verbose_name='Amount')),
                ('nights_charged', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nights Charged')),
                ('nights_in_period', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nights in Billing Period')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('end_date', models.DateField(blank=True, help_text='Blank = ongoing until removed', null=True, verbose_name='End Date')),
                ('is_recurring', models.BooleanField(default=False, help_text='Applies every billing cycle vs. a one-time adjustment (e.g. first-month proration)', verbose_name='Recurring')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_adjustments_created', to='users.landlordprofile')),
                ('lease_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_adjustments', to='leases.leasetenant')),
            ],
            options={
                'verbose_name': 'Rent Adjustment',
                'verbose_name_plural': 'Rent Adjustments',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='rent_adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='leases.rentadjustment'),
        ),
    ]
