# Generated by Django 5.0.12 on 2026-07-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_alter_leasetenant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasetenant',
            name='decline_reason',
            field=models.TextField(blank=True, verbose_name='Decline Reason'),
        ),
        migrations.AddField(
            model_name='leasetenant',
            name='declined',
            field=models.BooleanField(default=False, verbose_name='Declined'),
        ),
        migrations.AddField(
            model_name='leasetenant',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Declined'),
        ),
    ]
