# Generated by Django 5.0.12 on 2026-07-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0005_leasetenant_decline_reason_leasetenant_declined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='total_rent',
            field=models.DecimalField(decimal_places=2, default=0, help_text="The full monthly rent for the unit/room(s) under this lease. Individual tenants' rent_amount values should sum to this.", max_digits=10, verbose_name='Total Monthly Rent'),
        ),
        migrations.AlterField(
            model_name='leasetenant',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, help_text="This tenant's share of Lease.total_rent — used for internal accounting/splits only. Per the joint-and-several policy (see Lease.check_and_activate()), tenants should always be shown Lease.total_rent as 'their' rent in tenant-facing UI, never this per-tenant share, so nobody is nudged toward paying only a partial amount.", max_digits=10, verbose_name='Individual Monthly Rent'),
        ),
    ]
