# Generated by Django 5.0.12 on 2026-07-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0006_lease_total_rent_alter_leasetenant_rent_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='lease_type',
            field=models.CharField(choices=[('BC_ROOMMATE', 'BC TRAC Roommate Agreement'), ('SK_ROOMMATE', 'Saskatchewan Roommate Agreement'), ('BC_RESIDENTIAL', 'BC Residential Tenancy (RTB-1)'), ('SK_RESIDENTIAL', 'Saskatchewan Residential Tenancy'), ('GENERIC_RESIDENTIAL', 'Standard Residential Agreement'), ('GENERIC_ROOMMATE', 'Standard Roommate Agreement')], max_length=25, verbose_name='Lease Type'),
        ),
    ]
