# Generated by Django 5.0.12 on 2026-07-02 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0007_alter_lease_lease_type'),
        ('properties', '0007_area_area_area_belongs_to_group_xor_property'),
        ('users', '0005_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('move_in', models.DateField(verbose_name='Move-in')),
                ('move_out', models.DateField(blank=True, help_text='Blank = ongoing.', null=True, verbose_name='Move-out')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupancies', to='leases.lease')),
                ('room', models.ForeignKey(help_text='The room (for group/roommate setups) or the whole unit.', on_delete=django.db.models.deletion.PROTECT, related_name='occupancies', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancies', to='users.tenantprofile')),
            ],
            options={
                'verbose_name': 'Occupancy',
                'verbose_name_plural': 'Occupancies',
                'ordering': ['room', 'move_in'],
                'indexes': [models.Index(fields=['room', 'move_in'], name='leases_occu_room_id_086ac7_idx'), models.Index(fields=['tenant', 'move_in'], name='leases_occu_tenant__2612a1_idx')],
            },
        ),
    ]
