# Generated by Django 5.0.12 on 2026-07-05 01:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0008_occupancy'),
        ('maintenance', '0001_initial'),
        ('properties', '0007_area_area_area_belongs_to_group_xor_property'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('province', models.CharField(choices=[('BC', 'British Columbia'), ('SK', 'Saskatchewan'), ('GENERIC', 'Generic')], db_index=True, max_length=10, verbose_name='Province')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inspection Template',
                'verbose_name_plural': 'Inspection Templates',
                'ordering': ['province', '-version'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(help_text="RTB-27 room/section, e.g. 'Kitchen'.", max_length=60, verbose_name='Section')),
                ('label', models.CharField(help_text="Line item, e.g. 'Walls and Trim'.", max_length=120, verbose_name='Item')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'Inspection Template Item',
                'verbose_name_plural': 'Inspection Template Items',
                'ordering': ['template', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ConditionInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('MOVE_IN_IN_PROGRESS', 'Move-in — In Progress'), ('MOVE_IN_SIGNED', 'Move-in Signed'), ('MOVE_OUT_IN_PROGRESS', 'Move-out — In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='MOVE_IN_IN_PROGRESS', max_length=25, verbose_name='Status')),
                ('possession_date', models.DateField(blank=True, null=True, verbose_name='Possession Date')),
                ('move_in_inspection_date', models.DateField(blank=True, null=True, verbose_name='Move-in Inspection Date')),
                ('move_out_date', models.DateField(blank=True, null=True, verbose_name='Move-out Date')),
                ('move_out_inspection_date', models.DateField(blank=True, null=True, verbose_name='Move-out Inspection Date')),
                ('tenant_agent_move_in', models.CharField(blank=True, max_length=150, verbose_name="Tenant's Agent (move-in)")),
                ('tenant_agent_move_out', models.CharField(blank=True, max_length=150, verbose_name="Tenant's Agent (move-out)")),
                ('repairs_required_at_start', models.TextField(blank=True, verbose_name='Repairs Required at Start (Box X)')),
                ('tenant_responsible_damage', models.TextField(blank=True, verbose_name='Tenant-Responsible Damage (Box Z)')),
                ('tenant_agrees_move_in', models.BooleanField(blank=True, null=True, verbose_name='Tenant Agrees (move-in)')),
                ('tenant_disagreement_move_in', models.TextField(blank=True, verbose_name='Disagreement Reason (move-in)')),
                ('tenant_agrees_move_out', models.BooleanField(blank=True, null=True, verbose_name='Tenant Agrees (move-out)')),
                ('tenant_disagreement_move_out', models.TextField(blank=True, verbose_name='Disagreement Reason (move-out)')),
                ('landlord_signed_move_in_at', models.DateTimeField(blank=True, null=True)),
                ('landlord_move_in_signature_name', models.CharField(blank=True, max_length=150)),
                ('tenant_signed_move_in_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_move_in_signature_name', models.CharField(blank=True, max_length=150)),
                ('landlord_signed_move_out_at', models.DateTimeField(blank=True, null=True)),
                ('landlord_move_out_signature_name', models.CharField(blank=True, max_length=150)),
                ('tenant_signed_move_out_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_move_out_signature_name', models.CharField(blank=True, max_length=150)),
                ('deduction_security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Agreed Deduction — Security Deposit')),
                ('deduction_pet_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Agreed Deduction — Pet Deposit')),
                ('deduction_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_forwarding_address', models.CharField(blank=True, max_length=255)),
                ('move_in_report_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('move_out_report_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_created', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='leases.lease')),
                ('lease_tenant', models.ForeignKey(blank=True, help_text='Set for room/group leases; NULL for complete-unit leases.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='leases.leasetenant')),
            ],
            options={
                'verbose_name': 'Condition Inspection',
                'verbose_name_plural': 'Condition Inspections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AreaConditionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('GOOD', 'Good (✓)'), ('FAIR', 'Fair (F)'), ('POOR', 'Poor (P)'), ('MISSING', 'Missing (M)'), ('DAMAGED', 'Damaged (D)'), ('SCRATCHED', 'Scratched (S)'), ('BROKEN', 'Broken (B)')], default='GOOD', max_length=10, verbose_name='Condition')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='condition_state', to='properties.area')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_inspection', models.ForeignKey(blank=True, help_text='The inspection whose completion last wrote this, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leases.conditioninspection')),
            ],
            options={
                'verbose_name': 'Area Condition',
                'verbose_name_plural': 'Area Conditions',
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=60, verbose_name='Section')),
                ('label', models.CharField(max_length=200, verbose_name='Item')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_custom', models.BooleanField(default=False, help_text="Landlord-added row (the form's blank lines).")),
                ('move_in_condition_code', models.CharField(blank=True, choices=[('GOOD', 'Good (✓)'), ('FAIR', 'Fair (F)'), ('POOR', 'Poor (P)'), ('MISSING', 'Missing (M)'), ('DAMAGED', 'Damaged (D)'), ('SCRATCHED', 'Scratched (S)'), ('BROKEN', 'Broken (B)')], default='', max_length=10)),
                ('move_in_cleanliness_code', models.CharField(blank=True, choices=[('DIRTY', 'Dirty (DT)'), ('STAINED', 'Stained (ST)')], default='', max_length=10)),
                ('move_in_comment', models.CharField(blank=True, max_length=255)),
                ('move_out_condition_code', models.CharField(blank=True, choices=[('GOOD', 'Good (✓)'), ('FAIR', 'Fair (F)'), ('POOR', 'Poor (P)'), ('MISSING', 'Missing (M)'), ('DAMAGED', 'Damaged (D)'), ('SCRATCHED', 'Scratched (S)'), ('BROKEN', 'Broken (B)')], default='', max_length=10)),
                ('move_out_cleanliness_code', models.CharField(blank=True, choices=[('DIRTY', 'Dirty (DT)'), ('STAINED', 'Stained (ST)')], default='', max_length=10)),
                ('move_out_comment', models.CharField(blank=True, max_length=255)),
                ('needs_attention', models.BooleanField(default=False)),
                ('suggestion_status', models.CharField(choices=[('NONE', 'No suggestion'), ('PENDING', 'Pending landlord review'), ('APPROVED', 'Approved — work order created'), ('DISMISSED', 'Dismissed')], default='NONE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_items', to='properties.area')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='leases.conditioninspection')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_items', to='properties.inventoryitem')),
                ('shared_inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_items', to='properties.sharedinventoryitem')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_items', to='maintenance.workorder')),
            ],
            options={
                'verbose_name': 'Inspection Item',
                'verbose_name_plural': 'Inspection Items',
                'ordering': ['inspection', 'sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionKeyRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_type', models.CharField(max_length=120, verbose_name='Type of key or control')),
                ('issued_count', models.PositiveIntegerField(default=0, verbose_name='# Issued at start')),
                ('returned_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='# Returned at end')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_rows', to='leases.conditioninspection')),
            ],
            options={
                'verbose_name': 'Inspection Key Row',
                'verbose_name_plural': 'Inspection Key Rows',
                'ordering': ['inspection', 'sort_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='inspectiontemplate',
            constraint=models.UniqueConstraint(fields=('province', 'version'), name='uniq_template_province_version'),
        ),
        migrations.AddField(
            model_name='conditioninspection',
            name='template',
            field=models.ForeignKey(help_text='Provenance: which template version seeded this document.', on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='leases.inspectiontemplate'),
        ),
        migrations.AddField(
            model_name='inspectiontemplateitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='leases.inspectiontemplate'),
        ),
        migrations.AddConstraint(
            model_name='conditioninspection',
            constraint=models.UniqueConstraint(condition=models.Q(('lease_tenant__isnull', False)), fields=('lease', 'lease_tenant'), name='uniq_inspection_per_lease_tenant'),
        ),
        migrations.AddConstraint(
            model_name='conditioninspection',
            constraint=models.UniqueConstraint(condition=models.Q(('lease_tenant__isnull', True)), fields=('lease',), name='uniq_inspection_per_unit_lease'),
        ),
    ]
