# Generated by Django 5.0.12 on 2026-07-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0009_inspectiontemplate_inspectiontemplateitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasetenant',
            name='invited_name',
            field=models.CharField(blank=True, default='', help_text='Full legal name as entered by the landlord when inviting — used to fill the lease form (RTB-1 parties/signature blocks) before the tenant registers. Once the tenant links an account, their account name is authoritative and this becomes a fallback.', max_length=150, verbose_name='Invited Name'),
        ),
        migrations.AlterField(
            model_name='leasetenant',
            name='invited_email',
            field=models.EmailField(blank=True, help_text="Email the invite was sent to. Used to auto-link a TenantProfile on signup (or immediately, if an account with this email already exists) and as the pre-link identity in tenant lists and lease documents. Referenced by Meta.ordering, clean(), __str__, and the serializer's duplicate-invite guard — do not remove.", max_length=254, verbose_name='Invited Email'),
        ),
    ]
