# Generated by Django 5.0.12 on 2026-07-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0010_leasetenant_invited_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='etransfer_email',
            field=models.EmailField(blank=True, help_text="Where tenants should send their e-transfers for this lease. Shown in the tenant dashboard's 'Make a Payment' section. Falls back to the landlord service email, then the landlord's account email — see get_effective_etransfer_email().", max_length=254, verbose_name='e-Transfer Email'),
        ),
    ]
