# Generated by Django 5.0.12 on 2026-07-10 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0011_lease_etransfer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='custom_tenant_notice_months',
            field=models.PositiveSmallIntegerField(default=1, help_text='Months of notice the tenant must give to end this tenancy. Honored ONLY when the provincial tenancy act does not apply — i.e. the landlord (or their relatives) shares kitchen/common areas with the tenancy (RTA s.4(c) exemption). When the act applies, its statutory minimums override this.', verbose_name='Tenant Notice Period (months)'),
        ),
        migrations.CreateModel(
            name='MoveOutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initiated_by', models.CharField(choices=[('TENANT', 'Tenant'), ('LANDLORD', 'Landlord')], max_length=10)),
                ('kind', models.CharField(choices=[('TENANT_NOTICE', 'Tenant Notice to End Tenancy'), ('LANDLORD_NOTICE', 'Landlord Notice (Landlord Use)'), ('MUTUAL_AGREEMENT', 'Mutual Agreement to End Tenancy')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting Signature'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('requested_end_date', models.DateField(help_text='The date the tenancy is proposed to end (tenant vacates by 1 p.m.).', verbose_name='Requested End Date')),
                ('effective_end_date', models.DateField(blank=True, help_text='Set on acceptance — the date the tenancy actually ends.', null=True, verbose_name='Effective End Date')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('decline_reason', models.TextField(blank=True, verbose_name='Decline Reason')),
                ('form_type', models.CharField(blank=True, help_text='e.g. RTB-8 for BC mutual agreements.', max_length=20, verbose_name='Agreement Form')),
                ('rent_handling', models.CharField(choices=[('NONE', 'Keep final month as billed'), ('VOID_FINAL', "Void the final month's rent"), ('PRORATE_FINAL', 'Prorate the final month (credit unused days)')], default='NONE', help_text="For mutual agreements: what happens to the final month's rent once accepted. Chosen by the landlord.", max_length=15)),
                ('tenant_signed', models.BooleanField(default=False)),
                ('tenant_signed_at', models.DateTimeField(blank=True, null=True)),
                ('landlord_signed', models.BooleanField(default=False)),
                ('landlord_signed_at', models.DateTimeField(blank=True, null=True)),
                ('rules_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moveout_requests', to='leases.lease')),
                ('lease_tenant', models.ForeignKey(blank=True, help_text='The tenant slot that initiated / is named on the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moveout_requests', to='leases.leasetenant')),
            ],
            options={
                'verbose_name': 'Move-Out Request',
                'verbose_name_plural': 'Move-Out Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
