# Generated by Django 5.0.12 on 2026-07-12 01:08

import rentium.core.phone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0012_lease_custom_tenant_notice_months_moveoutrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='house_rules',
            field=models.TextField(blank=True, help_text='Shared-living ground rules: guests, quiet hours, cleaning rota, kitchen etiquette. Rendered as its own section of the roommate agreement. Not used for complete-unit tenancies.', verbose_name='House Rules'),
        ),
        migrations.AddField(
            model_name='lease',
            name='occupants',
            field=models.JSONField(blank=True, default=list, help_text="Names of people who will live in the unit but are NOT tenants on this agreement — children, a partner who isn't signing. They have no tenancy rights and no rent obligation; naming them is what stops their presence being an unauthorised occupant later.", verbose_name='Other Occupants'),
        ),
        migrations.AddField(
            model_name='lease',
            name='parking_description',
            field=models.CharField(blank=True, help_text="e.g. 'One uncovered stall, driveway, left side'", max_length=200, verbose_name='Parking Details'),
        ),
        migrations.AddField(
            model_name='lease',
            name='parking_extra_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Parking Charge (if not included)'),
        ),
        migrations.AddField(
            model_name='lease',
            name='parking_included',
            field=models.BooleanField(default=False, verbose_name='Parking Included'),
        ),
        migrations.AddField(
            model_name='lease',
            name='pet_deposit_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pet Damage Deposit Received On'),
        ),
        migrations.AddField(
            model_name='lease',
            name='pets_terms',
            field=models.TextField(blank=True, help_text='Conditions if pets are allowed — number, size, type, where.', verbose_name='Pet Terms'),
        ),
        migrations.AddField(
            model_name='lease',
            name='rent_due_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='The day rent is payable each period. The ledger currently generates charges on the 1st (see ledger/billing.py); this states the agreed day on the document, and is what the billing engine should read once non-1st due dates are supported.', verbose_name='Rent Due On (day of month)'),
        ),
        migrations.AddField(
            model_name='lease',
            name='security_deposit_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='Security Deposit Received On'),
        ),
        migrations.AddField(
            model_name='lease',
            name='services_and_facilities',
            field=models.JSONField(blank=True, default=list, help_text="Subset of ServiceOrFacility. A CONTRACTUAL statement of what the rent buys — distinct from bills_included, which is the billing split. See ServiceOrFacility's docstring.", verbose_name='Services and Facilities Included in Rent'),
        ),
        migrations.AddField(
            model_name='lease',
            name='smoking_terms',
            field=models.TextField(blank=True, help_text='Conditions or restrictions on smoking, if any.', verbose_name='Smoking Terms'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='landlord_daytime_phone',
            field=rentium.core.phone.PhoneField(blank=True, default='', max_length=20, verbose_name='Landlord Daytime Phone'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='landlord_other_phone',
            field=rentium.core.phone.PhoneField(blank=True, default='', max_length=20, verbose_name='Landlord Other Phone'),
        ),
        migrations.AlterField(
            model_name='leasetenant',
            name='invited_phone',
            field=rentium.core.phone.PhoneField(blank=True, default='', max_length=20, verbose_name='Invited Phone'),
        ),
    ]
