# Generated by Django 5.0.12 on 2026-07-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0013_lease_house_rules_lease_occupants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='signed_document',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Signed Document Snapshot'),
        ),
        migrations.AddField(
            model_name='lease',
            name='signed_document_sha256',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, verbose_name='Signed Document Checksum'),
        ),
    ]
