# Generated by Django 5.0.12 on 2026-07-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0014_lease_signed_document_lease_signed_document_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='co_hosts',
            field=models.JSONField(blank=True, default=list, verbose_name='Co-hosts'),
        ),
    ]
