# Generated by Django 5.0.12 on 2026-07-22 04:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0015_lease_co_hosts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseLandlordSignatory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('has_signed', models.BooleanField(default=False)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_signatories', to='leases.lease')),
                ('member', models.ForeignKey(blank=True, help_text='Set once the invited co-landlord has an account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_landlord_signatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='leaselandlordsignatory',
            constraint=models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('lease', 'email'), name='uniq_lease_signatory_email'),
        ),
    ]
