# Generated by Django 5.0.12 on 2026-07-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0017_alter_areaconditionstate_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveoutrequest',
            name='deposit_settlement',
            field=models.CharField(choices=[('PENDING', 'Not settled yet'), ('RETURNED', 'Returned in full'), ('AGREED', 'Tenant agreed in writing to a deduction'), ('RTB', 'Applied to the RTB for dispute resolution')], default='PENDING', max_length=12, verbose_name='Deposit Settlement'),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='forwarding_address',
            field=models.TextField(blank=True, help_text='Where the deposit is to be sent, as given in writing.', verbose_name='Forwarding Address'),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='forwarding_address_received_on',
            field=models.DateField(blank=True, help_text='Starts the 15-day clock, if later than the tenancy end.', null=True, verbose_name='Forwarding Address Received'),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='rtb_file_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='tenant_agreement_signed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
