# Generated by Django 5.0.12 on 2026-07-30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0018_moveoutrequest_deposit_settlement_and_more"),
        ("users", "0006_alter_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaseInviteEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SENT", "Invite sent"),
                            ("LINK_OPENED", "Invite link opened"),
                            ("ACCOUNT_LINKED", "Account linked"),
                            ("SIGNED", "Lease signed"),
                            ("DECLINED", "Lease declined"),
                            ("RESENT", "Invite resent"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lease_invite_events",
                        to="users.user",
                    ),
                ),
                (
                    "lease_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_events",
                        to="leases.leasetenant",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["lease_tenant", "kind", "-created_at"],
                        name="lease_invite_event_kind_idx",
                    )
                ],
            },
        ),
    ]
