# Generated by Django 5.0.12 on 2026-08-02 07:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0022_cleaning_deposit_received_date'),
        ('maintenance', '0005_workorder_responsible_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conditioninspection',
            name='deduction_cleaning_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Agreed Deduction — Cleaning Deposit'),
        ),
        migrations.CreateModel(
            name='DepositDeduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deposit_kind', models.CharField(choices=[('SECURITY', 'Security deposit'), ('PET', 'Pet damage deposit'), ('CLEANING', 'Cleaning deposit')], db_index=True, help_text='Deposits are held and returned separately, so every deduction has to name which one it comes out of.', max_length=10, verbose_name='Taken from')),
                ('basis', models.CharField(choices=[('LABOUR', 'Own labour (hours × rate)'), ('SUPPLIES', 'Cleaning supplies / materials'), ('CLEANER', 'Professional cleaners'), ('GARBAGE', 'Garbage removal / dumping fees'), ('OTHER', 'Other')], max_length=10, verbose_name='Basis')),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Hours')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Hourly Rate')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount')),
                ('note', models.TextField(blank=True, help_text='What was cleaned, hauled or repaired. A bare amount with no description is the deduction that loses a hearing.', verbose_name='What this covers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_deductions_created', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_deductions', to='leases.conditioninspection')),
                ('inspection_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_deductions', to='leases.inspectionitem')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_deductions', to='maintenance.workorder')),
            ],
            options={
                'verbose_name': 'Deposit Deduction',
                'verbose_name_plural': 'Deposit Deductions',
                'ordering': ['inspection', 'created_at'],
                'indexes': [models.Index(fields=['inspection', 'deposit_kind'], name='deposit_deduction_kind_idx')],
            },
        ),
    ]
