# Generated by Django 5.0.12 on 2026-08-04 03:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0024_alter_leaseinviteevent_kind'),
        ('users', '0009_remove_landlordteammember_uniq_team_owner_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent for signature'), ('PARTIAL', 'Partially signed'), ('COMPLETED', 'Completed'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=15)),
                ('required', models.BooleanField(default=True, help_text='An optional form is tracked but never blocks or nags.')),
                ('blocks_activation', models.BooleanField(default=False)),
                ('placements_snapshot', models.JSONField(blank=True, default=list)),
                ('values', models.JSONField(blank=True, default=dict, help_text='Non-signature field values, keyed by placement key.')),
                ('executed_file', models.FileField(blank=True, max_length=500, null=True, upload_to='lease_forms/executed/%Y/%m/')),
                ('executed_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('web', 'Dashboard'), ('rama', 'RAMA chat'), ('system', 'System workflow')], default='web', max_length=10)),
                ('source_attachment_id', models.CharField(blank=True, default='', help_text='RamaAttachment id when the PDF arrived through chat/Telegram.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_forms', to='leases.lease')),
                ('moveout_request', models.ForeignKey(blank=True, help_text='Set for MOVE_OUT forms — completing this signs that request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_forms', to='leases.moveoutrequest')),
            ],
            options={
                'verbose_name': 'Lease Form',
                'verbose_name_plural': 'Lease Forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseFormSigner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('LANDLORD', 'Landlord'), ('CO_LANDLORD', 'Co-landlord'), ('TENANT', 'Tenant'), ('OTHER', 'Other party')], max_length=15)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Matches LeaseFormPlacement.signer_index.')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('sign_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, default='')),
                ('required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='leases.leaseform')),
                ('landlord_signatory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_signers', to='leases.leaselandlordsignatory')),
                ('lease_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_signers', to='leases.leasetenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_form_signers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lease Form Signer',
                'verbose_name_plural': 'Lease Form Signers',
                'ordering': ['form', 'role', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LeaseFormSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typed_name', models.CharField(help_text='The legal name the signer typed. Required for both methods.', max_length=200)),
                ('method', models.CharField(choices=[('TYPED', 'Typed name'), ('DRAWN', 'Drawn signature')], max_length=10)),
                ('signature_png', models.ImageField(blank=True, null=True, upload_to='lease_forms/signatures/%Y/%m/')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('template_sha256', models.CharField(blank=True, default='', help_text="The blank form's checksum at the moment this was signed.", max_length=64)),
                ('values_sha256', models.CharField(blank=True, default='', help_text='Checksum of the filled values the signer was shown.', max_length=64)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='leases.leaseform')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='leases.leaseformsigner')),
            ],
            options={
                'verbose_name': 'Lease Form Signature',
                'verbose_name_plural': 'Lease Form Signatures',
                'ordering': ['signed_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseFormEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CREATED', 'Form attached'), ('FIELDS_PLACED', 'Fields placed'), ('SENT', 'Sent for signature'), ('REMINDED', 'Reminder sent'), ('LINK_OPENED', 'Signing link opened'), ('SIGNED', 'Signed'), ('DECLINED', 'Declined'), ('COMPLETED', 'Fully executed'), ('VOIDED', 'Voided')], db_index=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_form_events', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='leases.leaseform')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='leases.leaseformsigner')),
            ],
            options={
                'verbose_name': 'Lease Form Event',
                'verbose_name_plural': 'Lease Form Events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseFormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_index=True, default='', help_text='Stable identifier for system forms, e.g. BC_RTB8.', max_length=40, verbose_name='Form Code')),
                ('name', models.CharField(max_length=200, verbose_name='Form Name')),
                ('purpose', models.TextField(blank=True, default='', help_text='One sentence saying what this form does. Shown in the picker and read by RAMA so it can tell a landlord what they are about to send.', verbose_name='Purpose')),
                ('jurisdiction', models.CharField(blank=True, default='', help_text='Province code the form belongs to, e.g. BC. Blank = anywhere.', max_length=10, verbose_name='Jurisdiction')),
                ('source', models.CharField(choices=[('SYSTEM', 'System catalogue'), ('CUSTOM', 'Landlord upload')], default='CUSTOM', max_length=10)),
                ('stage', models.CharField(choices=[('WITH_LEASE', 'Signed with the lease'), ('ADDENDUM', 'Addendum during the tenancy'), ('MOVE_OUT', 'Signed to end the tenancy'), ('UNCLASSIFIED', 'Not classified yet')], db_index=True, default='UNCLASSIFIED', max_length=20)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('COMING_SOON', 'Coming soon')], db_index=True, default='AVAILABLE', max_length=15)),
                ('binds_to', models.CharField(blank=True, default='', help_text="'moveout' means completing this form signs and accepts the linked MoveOutRequest. Blank means the form is evidence only.", max_length=20, verbose_name='Drives Workflow')),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='lease_form_templates/%Y/%m/', verbose_name='Blank Form PDF')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('page_count', models.PositiveSmallIntegerField(default=0)),
                ('page_sizes', models.JSONField(blank=True, default=list, help_text="[{'width': 612, 'height': 792}, ...] in PDF points, per page.")),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('suggested_stage', models.CharField(blank=True, choices=[('WITH_LEASE', 'Signed with the lease'), ('ADDENDUM', 'Addendum during the tenancy'), ('MOVE_OUT', 'Signed to end the tenancy'), ('UNCLASSIFIED', 'Not classified yet')], default='', max_length=20)),
                ('suggested_purpose', models.TextField(blank=True, default='')),
                ('suggestion_signals', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(blank=True, help_text='Null for a system form available to every landlord.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_form_templates', to='users.landlordprofile')),
            ],
            options={
                'verbose_name': 'Lease Form Template',
                'verbose_name_plural': 'Lease Form Templates',
                'ordering': ['jurisdiction', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeaseFormPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text="Stable slug for this box. Taken from the PDF's own AcroForm field name when it has one, so a filled RTB-8 is traceable field by field.", max_length=120, verbose_name='Field Key')),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('page', models.PositiveSmallIntegerField(default=0)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('kind', models.CharField(choices=[('SIGNATURE', 'Signature'), ('INITIALS', 'Initials'), ('DATE', 'Date signed'), ('NAME', 'Name'), ('TEXT', 'Text'), ('CHECKBOX', 'Checkbox')], max_length=15)),
                ('signer_role', models.CharField(choices=[('LANDLORD', 'Landlord'), ('CO_LANDLORD', 'Co-landlord'), ('TENANT', 'Tenant'), ('OTHER', 'Other party')], default='TENANT', max_length=15)),
                ('signer_index', models.PositiveSmallIntegerField(default=0, help_text='0-based: which tenant/co-landlord this box belongs to.')),
                ('auto_source', models.CharField(blank=True, default='', help_text='Whitelisted lease field to prefill from, e.g. tenant.display_name. See form_services.AUTO_SOURCES — an unknown key is an error, never a silent blank.', max_length=60, verbose_name='Prefill From')),
                ('required', models.BooleanField(default=True)),
                ('font_size', models.FloatField(default=10.0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='leases.leaseformtemplate')),
            ],
            options={
                'verbose_name': 'Lease Form Placement',
                'verbose_name_plural': 'Lease Form Placements',
                'ordering': ['page', 'order', 'y', 'x'],
            },
        ),
        migrations.AddField(
            model_name='leaseform',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='leases.leaseformtemplate'),
        ),
        migrations.AddConstraint(
            model_name='leaseformsigner',
            constraint=models.UniqueConstraint(fields=('form', 'role', 'order'), name='lease_form_signer_slot_unique'),
        ),
        migrations.AddConstraint(
            model_name='leaseformsignature',
            constraint=models.UniqueConstraint(fields=('signer',), name='lease_form_signature_once_per_signer'),
        ),
        migrations.AddIndex(
            model_name='leaseformevent',
            index=models.Index(fields=['form', 'kind', '-created_at'], name='lease_form_event_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseformtemplate',
            index=models.Index(fields=['landlord', '-created_at'], name='leases_leas_landlor_d3029b_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaseformtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('landlord__isnull', False), models.Q(('sha256', ''), _negated=True)), fields=('landlord', 'sha256'), name='lease_form_template_landlord_sha256_unique'),
        ),
        migrations.AddConstraint(
            model_name='leaseformtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('landlord__isnull', True), models.Q(('code', ''), _negated=True)), fields=('code',), name='lease_form_template_system_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='leaseformplacement',
            constraint=models.UniqueConstraint(fields=('template', 'key'), name='lease_form_placement_key_unique'),
        ),
        migrations.AddIndex(
            model_name='leaseform',
            index=models.Index(fields=['lease', 'status'], name='leases_leas_lease_i_63db49_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseform',
            index=models.Index(fields=['status', 'blocks_activation'], name='leases_leas_status_07536c_idx'),
        ),
    ]
