# Generated by Django 5.0.12 on 2026-08-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0026_backfill_lease_form_signers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseinviteevent',
            name='kind',
            field=models.CharField(choices=[('SENT', 'Invite sent'), ('LINK_OPENED', 'Invite link opened'), ('LEASE_VIEWED', 'Lease agreement viewed'), ('ACCOUNT_LINKED', 'Account linked'), ('SIGNED', 'Lease signed'), ('DECLINED', 'Lease declined'), ('RESENT', 'Invite resent'), ('TERMS_AMENDED', 'Terms amended after signing'), ('INVITE_REDIRECTED', 'Invite redirected to a new email')], db_index=True, max_length=30),
        ),
    ]
