# Generated by Django 5.0.12 on 2025-04-06 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Property Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('province', models.CharField(max_length=100, verbose_name='Province/State')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal/Zip Code')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance'), ('NOT_AVAILABLE', 'Not Available')], default='AVAILABLE', max_length=20, verbose_name='Status')),
                ('property_category', models.CharField(choices=[('COMPLETE_UNIT', 'Complete Unit'), ('ROOM', 'Room')], max_length=20, verbose_name='Property Category')),
                ('unit_type', models.CharField(blank=True, choices=[('BASEMENT', 'Basement'), ('GARDEN_SUITE', 'Garden Suite'), ('MAIN_FLOOR', 'Main Floor'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other')], max_length=20, null=True, verbose_name='Unit Type')),
                ('bedrooms', models.IntegerField(blank=True, null=True, verbose_name='Number of Bedrooms')),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Number of Bathrooms')),
                ('max_occupancy', models.IntegerField(blank=True, null=True, verbose_name='Maximum Occupancy')),
                ('square_footage', models.IntegerField(blank=True, null=True, verbose_name='Square Footage')),
                ('room_type', models.CharField(blank=True, choices=[('PRIVATE', 'Private Room'), ('SHARED', 'Shared Room'), ('OTHER', 'Other')], max_length=20, null=True, verbose_name='Room Type')),
                ('total_washrooms', models.IntegerField(blank=True, null=True, verbose_name='Total Washrooms in Property')),
                ('other_rooms', models.TextField(blank=True, help_text='Describe other rooms that tenants have access to', verbose_name='Other Rooms Available')),
                ('shared_with', models.TextField(blank=True, help_text='Describe who else lives in the property', verbose_name='Shared With')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='users.landlordprofile')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
