# Generated by Django 5.0.12 on 2025-04-07 07:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_primary_image_propertyimage'),
        ('users', '0005_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='other_rooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='property',
            name='total_washrooms',
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyimage_set', to='properties.property'),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Main Door Key, Queen Bed Frame, Microwave Oven', max_length=200, verbose_name='Item Name')),
                ('description', models.TextField(blank=True, verbose_name='Description/Notes')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('condition', models.CharField(blank=True, choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged'), ('MISSING', 'Missing')], max_length=10, null=True, verbose_name='Condition')),
                ('location_description', models.CharField(blank=True, help_text='Specific location within the property (e.g., Kitchen Drawer, Bedroom 1 Closet, Shared Hallway)', max_length=255, verbose_name='Location Description')),
                ('is_shared', models.BooleanField(default=False, help_text='Is this item part of a shared space/common asset pool (relevant for rooms in a group)?', verbose_name='Is Shared Asset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryitem_set', to='properties.property')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['property', 'location_description', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Unit 5 Shared Spaces, Basement Suite Rooms', max_length=100, verbose_name='Group Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_groups', to='users.landlordprofile')),
            ],
            options={
                'verbose_name': 'Property Group',
                'verbose_name_plural': 'Property Groups',
                'ordering': ['landlord', 'name'],
                'unique_together': {('landlord', 'name')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group this room belongs to (if sharing common areas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grouped_properties', to='properties.propertygroup', verbose_name='Property Group'),
        ),
        migrations.CreateModel(
            name='PropertyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(choices=[('KITCHEN', 'Kitchen'), ('BATHROOM', 'Bathroom'), ('LIVING_ROOM', 'Living Room'), ('DINING_ROOM', 'Dining Room'), ('BEDROOM', 'Bedroom'), ('LAUNDRY', 'Laundry Area'), ('OFFICE', 'Office/Den'), ('BALCONY', 'Balcony/Patio'), ('HALLWAY', 'Hallway/Entryway'), ('STORAGE', 'Storage Area'), ('GARAGE', 'Garage'), ('GARDEN', 'Garden/Yard'), ('OTHER', 'Other')], max_length=20, verbose_name='Area Type')),
                ('count', models.PositiveIntegerField(default=1, help_text='How many of this area type exist (e.g., 2 bathrooms)', verbose_name='Count')),
                ('is_shared', models.BooleanField(default=False, help_text='Is this area shared with other tenants (relevant for rooms in a group)?', verbose_name='Is Shared')),
                ('description', models.TextField(blank=True, help_text='Optional details about this area.', verbose_name='Area Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Area',
                'verbose_name_plural': 'Property Areas',
                'ordering': ['property', 'area_type'],
                'unique_together': {('property', 'area_type')},
            },
        ),
    ]
