# Generated by Django 5.0.12 on 2025-04-08 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_other_rooms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['property', 'location_description', 'name'], 'verbose_name': 'Private Inventory Item', 'verbose_name_plural': 'Private Inventory Items'},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='is_shared',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location_description',
            field=models.CharField(blank=True, help_text='Specific location within this property (e.g., Bedroom Closet)', max_length=255, verbose_name='Location Description'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(help_text='e.g., Bedside Lamp, Personal Desk Chair', max_length=200, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='propertyarea',
            name='count',
            field=models.PositiveIntegerField(default=1, help_text='e.g., 2 bathrooms', verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='propertyarea',
            name='description',
            field=models.TextField(blank=True, help_text='Optional details', verbose_name='Area Description'),
        ),
        migrations.AlterField(
            model_name='propertyarea',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Relevant for rooms in a group', verbose_name='Is Shared'),
        ),
        migrations.CreateModel(
            name='SharedInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Microwave Oven, Sofa, Communal Vacuum', max_length=200, verbose_name='Item Name')),
                ('description', models.TextField(blank=True, verbose_name='Description/Notes')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('condition', models.CharField(blank=True, choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged'), ('MISSING', 'Missing')], max_length=10, null=True, verbose_name='Condition')),
                ('location_description', models.CharField(blank=True, help_text='Specific location within the shared space (e.g., Kitchen Counter, Living Room Corner)', max_length=255, verbose_name='Location Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_items', to='properties.propertygroup')),
            ],
            options={
                'verbose_name': 'Shared Inventory Item',
                'verbose_name_plural': 'Shared Inventory Items',
                'ordering': ['group', 'location_description', 'name'],
            },
        ),
    ]
