# Generated by Django 5.0.12 on 2025-04-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyarea',
            name='is_private_to_room',
            field=models.BooleanField(default=False, help_text='Is this area exclusively for this specific room (e.g., ensuite)? Only applies to ROOM properties.', verbose_name='Private to Room'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location_description',
            field=models.CharField(blank=True, help_text='e.g., Bedroom Closet', max_length=255, verbose_name='Location Description'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(help_text='e.g., Bedside Lamp', max_length=200, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='propertyarea',
            name='is_shared',
            field=models.BooleanField(default=False, help_text="Is this area shared with everyone in the property's group?", verbose_name='Shared with Group'),
        ),
        migrations.AlterField(
            model_name='sharedinventoryitem',
            name='location_description',
            field=models.CharField(blank=True, help_text='e.g., Kitchen Counter', max_length=255, verbose_name='Location Description'),
        ),
        migrations.AlterField(
            model_name='sharedinventoryitem',
            name='name',
            field=models.CharField(help_text='e.g., Microwave Oven', max_length=200, verbose_name='Item Name'),
        ),
    ]
