# Generated by Django 5.0.12 on 2025-04-08 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertyarea_is_private_to_room_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertyarea',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='propertyarea',
            name='shared_by',
            field=models.ManyToManyField(blank=True, help_text='Select ROOM properties that share access to this area.', related_name='shared_areas', to='properties.property', verbose_name='Shared By Properties'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertyarea',
            name='count',
            field=models.PositiveIntegerField(default=1, help_text='e.g., Number of identical areas', verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='propertyarea',
            name='property',
            field=models.ForeignKey(help_text='The primary property this area belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='primary_area_associations', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='sharedinventoryitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_shared_inventory', to='properties.propertygroup'),
        ),
        migrations.RemoveField(
            model_name='propertyarea',
            name='is_private_to_room',
        ),
        migrations.RemoveField(
            model_name='propertyarea',
            name='is_shared',
        ),
    ]
