# Generated by Django 5.0.12 on 2026-07-02 15:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_propertyarea_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('kind', models.CharField(choices=[('COMMON', 'Common / Shared'), ('EXCLUSIVE', 'Exclusive to a Room'), ('SYSTEM', 'Building System')], default='COMMON', max_length=10, verbose_name='Kind')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exclusive_to', models.ForeignKey(blank=True, help_text='The room this area is reserved for (EXCLUSIVE kind only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusive_areas', to='properties.property')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='properties.propertygroup')),
                ('property', models.ForeignKey(blank=True, help_text='For standalone (non-group) units.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='properties.property')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('group__isnull', False), ('property__isnull', True)), models.Q(('group__isnull', True), ('property__isnull', False)), _connector='OR'), name='area_belongs_to_group_xor_property'),
        ),
    ]
