# Generated by Django 5.0.12 on 2026-07-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_area_area_area_belongs_to_group_xor_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyarea',
            name='shared_with_landlord',
            field=models.BooleanField(default=False, help_text='The landlord or their immediate relatives also live here and use this area (kitchen/bathroom/common space). Affects whether the provincial tenancy act applies to leases on these rooms.', verbose_name='Shared with Landlord'),
        ),
    ]
