# Generated by Django 5.0.12 on 2026-07-12 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_propertyarea_shared_with_landlord'),
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address_verified',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='property',
            name='asking_rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="What you're advertising this space for. Distinct from Lease.total_rent, which is what an ACTUAL tenancy costs — a vacant unit has no lease, so there'd be nothing to show a prospective tenant without this.", max_digits=10, null=True, verbose_name='Asking Rent (monthly)'),
        ),
        migrations.AddField(
            model_name='property',
            name='available_from',
            field=models.DateField(blank=True, help_text='Blank = available now.', null=True, verbose_name='Available From'),
        ),
        migrations.AddField(
            model_name='property',
            name='building_amenities',
            field=models.JSONField(blank=True, default=list, help_text="Complete units only. Building facilities this unit shares with other units (laundry, parking, storage...). A unit shares nothing else — a ROOM's shared spaces come from its property group's common areas.", verbose_name='Shared Building Amenities'),
        ),
        migrations.AddField(
            model_name='property',
            name='city_slug',
            field=models.SlugField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='geocoded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_furnished',
            field=models.BooleanField(default=False, editable=False, help_text="DERIVED, never entered by hand — computed from this property's inventory (see properties/furnishing.py) and refreshed by signal whenever inventory changes. Denormalised only so the public city page can filter on it in SQL.", verbose_name='Furnished'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_publicly_visible',
            field=models.BooleanField(default=True, help_text="Per-property override. Turning this off hides ONE property while leaving the rest of the landlord's public page intact. Has no effect unless the landlord has also opted in to public pages at all.", verbose_name='Show this property publicly'),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='neighbourhood',
            field=models.CharField(blank=True, help_text="Shown publicly INSTEAD of the street address. Auto-filled from geocoding; edit it if you'd rather show something else (or clear it to show only the city).", max_length=120, verbose_name='Neighbourhood'),
        ),
        migrations.AddField(
            model_name='property',
            name='province_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=2),
        ),
        migrations.AddField(
            model_name='property',
            name='public_slug',
            field=models.SlugField(blank=True, help_text='Auto-generated. Used in /<province>/<city>/<slug>/.', max_length=180, null=True, unique=True, verbose_name='Public URL slug'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(help_text="Start typing and pick from the list — we'll fill in the rest.", max_length=255, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(help_text='Filled in from the address you picked.', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(default='Canada', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='property',
            name='postal_code',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a Canadian postal code, like V8Z 3T7.', regex='^[A-Za-z]\\d[A-Za-z][ ]?\\d[A-Za-z]\\d$')], verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='property',
            name='province',
            field=models.CharField(blank=True, choices=[('ab', 'Alberta'), ('bc', 'British Columbia'), ('mb', 'Manitoba'), ('nb', 'New Brunswick'), ('nl', 'Newfoundland and Labrador'), ('ns', 'Nova Scotia'), ('nt', 'Northwest Territories'), ('nu', 'Nunavut'), ('on', 'Ontario'), ('pe', 'Prince Edward Island'), ('qc', 'Quebec'), ('sk', 'Saskatchewan'), ('yt', 'Yukon')], db_index=True, max_length=2, verbose_name='Province'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['province_code', 'city_slug', 'status'], name='properties__provinc_ede639_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_publicly_visible', 'status'], name='properties__is_publ_b439a3_idx'),
        ),
    ]
