# Generated by Django 5.0.12 on 2026-07-20 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_address_verified_property_asking_rent_and_more'),
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyHolding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., McKenzie House', max_length=100, verbose_name='Holding Name')),
                ('kind', models.CharField(choices=[('HOUSE', 'House'), ('BUILDING', 'Building'), ('OTHER', 'Other')], default='HOUSE', max_length=20)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_holdings', to='users.landlordprofile')),
            ],
            options={
                'verbose_name': 'Property Holding',
                'verbose_name_plural': 'Property Holdings',
                'ordering': ['landlord', 'name'],
                'unique_together': {('landlord', 'name')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='holding',
            field=models.ForeignKey(blank=True, help_text='The house/building this listing belongs to (one bank account).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='properties.propertyholding', verbose_name='Holding'),
        ),
    ]
