# Generated by Django 5.0.12 on 2026-07-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_propertyholding_property_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='default_bills_included',
            field=models.JSONField(blank=True, default=dict, help_text="Bills/utilities configuration inherited by NEW leases created on this property (same shape as Lease.bills_included). Lets a landlord set 'water included, hydro tenant-paid' once, so future leases start with it pre-filled instead of blank.", verbose_name='Default Bills / Utilities'),
        ),
    ]
