# Generated by Django 5.0.12 on 2026-07-26 01:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_propertyarea_is_group_common'),
        ('users', '0009_remove_landlordteammember_uniq_team_owner_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_active_offering',
            field=models.BooleanField(db_index=True, default=True, help_text='False for listings parked by a rental-mode switch.', verbose_name='Active Offering'),
        ),
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Main Floor, Basement, Upstairs, Garden Suite', max_length=100, verbose_name='Unit Name')),
                ('unit_type', models.CharField(blank=True, choices=[('BASEMENT', 'Basement'), ('GARDEN_SUITE', 'Garden Suite'), ('MAIN_FLOOR', 'Main Floor'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other')], max_length=20, verbose_name='Unit Type')),
                ('rental_mode', models.CharField(choices=[('WHOLE_UNIT', 'Rented as one whole unit'), ('BY_ROOM', 'Rented room by room')], db_index=True, default='WHOLE_UNIT', help_text='Whether this unit is currently offered whole or room by room.', max_length=20, verbose_name='Rental Mode')),
                ('layout_complete', models.BooleanField(default=False, help_text='False when we know some rooms/bathrooms are still unrecorded.', verbose_name='Layout Complete')),
                ('missing_layout_notes', models.TextField(blank=True, help_text="What is known to be missing, in the landlord's own words.", verbose_name='Missing Layout Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holding', models.ForeignKey(help_text='The address this unit is part of.', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.propertyholding', verbose_name='Holding')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_units', to='users.landlordprofile')),
            ],
            options={
                'verbose_name': 'Property Unit',
                'verbose_name_plural': 'Property Units',
                'ordering': ['holding', 'name'],
                'unique_together': {('holding', 'name')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='The physical floor/suite this listing rents out.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='properties.propertyunit', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='propertygroup',
            name='unit',
            field=models.OneToOneField(blank=True, help_text='The physical unit these rooms make up.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_group', to='properties.propertyunit', verbose_name='Unit'),
        ),
    ]
