# Generated by Django 5.0.12 on 2026-07-26 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0017_alter_areaconditionstate_area_and_more'),
        ('maintenance', '0003_alter_workorder_area'),
        ('properties', '0013_property_is_active_offering_propertyunit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='exclusive_to',
        ),
        migrations.RemoveField(
            model_name='area',
            name='group',
        ),
        migrations.RemoveField(
            model_name='area',
            name='property',
        ),
        migrations.AlterModelOptions(
            name='propertyarea',
            options={'ordering': ['kind', 'name', 'area_type'], 'verbose_name': 'Property Area', 'verbose_name_plural': 'Property Areas'},
        ),
        migrations.AddField(
            model_name='propertyarea',
            name='exclusive_to',
            field=models.ForeignKey(blank=True, help_text='The room this area is reserved for (EXCLUSIVE kind only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusive_areas', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyarea',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The room-rental group this shared space belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='properties.propertygroup'),
        ),
        migrations.AddField(
            model_name='propertyarea',
            name='kind',
            field=models.CharField(choices=[('COMMON', 'Common / Shared'), ('PRIVATE', 'Private to one space'), ('EXCLUSIVE', 'Exclusive to a Room'), ('SYSTEM', 'Building System')], default='COMMON', max_length=10, verbose_name='Kind'),
        ),
        migrations.AddField(
            model_name='propertyarea',
            name='name',
            field=models.CharField(blank=True, help_text='e.g., Master Bedroom, Ensuite. Falls back to the area type.', max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='propertyarea',
            name='serves_areas',
            field=models.ManyToManyField(blank=True, help_text='The bedrooms/spaces this area serves, if not all of them.', related_name='served_by_areas', to='properties.propertyarea', verbose_name='Serves Areas'),
        ),
        migrations.AddField(
            model_name='propertyarea',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='The physical unit this space is part of.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='properties.propertyunit'),
        ),
        migrations.AlterField(
            model_name='propertyarea',
            name='area_type',
            field=models.CharField(choices=[('KITCHEN', 'Kitchen'), ('BATHROOM', 'Bathroom'), ('LIVING_ROOM', 'Living Room'), ('DINING_ROOM', 'Dining Room'), ('BEDROOM', 'Bedroom'), ('LAUNDRY', 'Laundry Area'), ('OFFICE', 'Office/Den'), ('BALCONY', 'Balcony/Patio'), ('HALLWAY', 'Hallway/Entryway'), ('STORAGE', 'Storage Area'), ('GARAGE', 'Garage'), ('GARDEN', 'Garden/Yard'), ('HEATING', 'Heating / Furnace'), ('HOT_WATER', 'Hot Water'), ('ELECTRICAL', 'Electrical Panel'), ('ROOF', 'Roof / Structure'), ('OTHER', 'Other')], max_length=20, verbose_name='Area Type'),
        ),
        migrations.AlterField(
            model_name='propertyarea',
            name='property',
            field=models.ForeignKey(blank=True, help_text='The primary property this area belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_area_associations', to='properties.property'),
        ),
        migrations.AddConstraint(
            model_name='propertyarea',
            constraint=models.CheckConstraint(check=models.Q(('unit__isnull', False), ('group__isnull', False), ('property__isnull', False), _connector='OR'), name='area_has_a_parent'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
