# Generated by Django 5.0.12 on 2026-07-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_remove_area_exclusive_to_remove_area_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyarea',
            name='is_seeded_default',
            field=models.BooleanField(db_index=True, default=False, help_text='Auto-created placeholder, not a recorded layout fact.', verbose_name='Seeded Default'),
        ),
    ]
