# Generated by Django 5.0.12 on 2026-07-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_propertyarea_is_seeded_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='furnishing_details',
            field=models.TextField(blank=True, help_text="Optional note for the lease/listing, e.g. 'bed and dresser only' or 'tenant must supply mattress'.", verbose_name='Furnishing details'),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(choices=[('UNFURNISHED', 'Unfurnished'), ('SEMI_FURNISHED', 'Semi-furnished'), ('FURNISHED', 'Furnished')], default='UNFURNISHED', help_text='What you advertise and put on the lease: unfurnished, semi-furnished, or furnished. Inventory still lists specific items; this is the one-word choice for the agreement.', max_length=20, verbose_name='Furnishing'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_furnished',
            field=models.BooleanField(default=False, editable=False, help_text='DERIVED cache for public SQL filters. True when furnishing_status is furnished/semi-furnished, or inventory contains a bed (see properties/furnishing.py). Not entered by hand.', verbose_name='Furnished (filter cache)'),
        ),
    ]
