# Generated by Django 5.0.12 on 2026-07-13 02:15

import django.core.validators
import django.db.models.deletion
import rentium.core.phone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_alter_appointment_contact_phone'),
        ('properties', '0009_property_address_verified_property_asking_rent_and_more'),
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_public', models.BooleanField(default=False, help_text='OFF by default and stays off until the landlord explicitly turns it on. While off, /l/<slug> 404s and none of their properties appear on any city page or in the sitemap.', verbose_name='Show my properties publicly')),
                ('slug', models.SlugField(blank=True, help_text='Their page lives at /l/<slug>. Renameable; old slugs redirect.', max_length=60, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers and hyphens only — e.g. raj-rentals. No spaces, no leading or trailing hyphen.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$'), django.core.validators.MinLengthValidator(3)], verbose_name='Public URL')),
                ('display_name', models.CharField(blank=True, help_text="Shown publicly instead of their account name. Blank falls back to the account name — they may prefer 'McKenzie Rentals' to their legal name.", max_length=120, verbose_name='Display Name')),
                ('bio', models.TextField(blank=True, help_text='Optional. A few sentences for prospective tenants.', max_length=1200, verbose_name='About')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='showcase/%Y/%m/', verbose_name='Photo or Logo')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Inquiry Email')),
                ('first_published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='showcase', to='users.landlordprofile')),
            ],
            options={
                'verbose_name': 'Showcase Page',
                'verbose_name_plural': 'Showcase Pages',
            },
        ),
        migrations.CreateModel(
            name='ShowcaseSlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('retired_at', models.DateTimeField(auto_now_add=True)),
                ('showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_history', to='showcase.showcase')),
            ],
            options={
                'verbose_name': 'Retired Showcase URL',
                'verbose_name_plural': 'Retired Showcase URLs',
                'ordering': ['-retired_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', rentium.core.phone.PhoneField(blank=True, default='', max_length=20, verbose_name='Phone')),
                ('message', models.TextField(max_length=2000, verbose_name='Message')),
                ('move_in_target', models.DateField(blank=True, null=True, verbose_name='Hoping to move in')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REPLIED', 'Replied'), ('ARCHIVED', 'Archived'), ('SPAM', 'Spam')], db_index=True, default='NEW', max_length=10)),
                ('landlord_notes', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='appointments.appointment')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='users.landlordprofile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['landlord', 'status', 'created_at'], name='showcase_in_landlor_42d4b5_idx')],
            },
        ),
    ]
