# Generated by Django 5.0.12 on 2026-07-21 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_remove_conversation_uniq_conversation_scope_and_more'),
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='messaging.conversation'),
        ),
    ]
