# Generated by Django 5.0.12 on 2026-07-21 01:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0014_lease_signed_document_lease_signed_document_sha256'),
        ('messaging', '0001_initial'),
        ('properties', '0010_propertyholding_property_holding'),
        ('users', '0007_landlordprofile_timezone'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='uniq_conversation_scope',
        ),
        migrations.AddField(
            model_name='conversation',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_conversations', to='properties.property'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='prospect_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Prospect email'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='prospect_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prospect name'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='users.tenantprofile'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('landlord', 'tenant', 'lease'), name='uniq_conversation_scope'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('tenant__isnull', False), ('prospect_email', '')), models.Q(('tenant__isnull', True), models.Q(('prospect_email', ''), _negated=True)), _connector='OR'), name='conversation_tenant_xor_prospect'),
        ),
    ]
