# Generated by Django 5.0.12 on 2026-07-20 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('TELEGRAM', 'Telegram'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], default='TELEGRAM', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('verified', models.BooleanField(default=False)),
                ('link_code', models.CharField(blank=True, default='', max_length=12)),
                ('link_code_expires', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('prefs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_accounts', to='users.landlordprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='channelaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('address', ''), _negated=True), fields=('channel_type', 'address'), name='comms_channel_address_unique'),
        ),
    ]
