# Generated by Django 5.0.12 on 2026-07-20 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
        ('users', '0007_landlordprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelaccount',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_accounts', to='users.tenantprofile'),
        ),
        migrations.AlterField(
            model_name='channelaccount',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_accounts', to='users.landlordprofile'),
        ),
        migrations.AddConstraint(
            model_name='channelaccount',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('landlord__isnull', False), ('tenant__isnull', True)), models.Q(('landlord__isnull', True), ('tenant__isnull', False)), _connector='OR'), name='comms_channel_one_subject'),
        ),
    ]
