# Generated by Django 5.0.12 on 2026-07-16 23:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0006_alter_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="RamaAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("conversation_id", models.UUIDField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("USER_MESSAGE", "User message"),
                            ("ASSISTANT_MESSAGE", "Assistant message"),
                            ("TOOL_CALL", "Tool call"),
                            ("ERROR", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=40)),
                ("model", models.CharField(blank=True, default="", max_length=100)),
                ("content", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rama_audits",
                        to="users.landlordprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["landlord", "conversation_id", "created_at"],
                        name="rama_ramaau_landlor_68c640_idx",
                    )
                ],
            },
        ),
    ]
