# Generated by Django 5.0.12 on 2026-07-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamaConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Master switch. When off, chat returns 403; state-of-the-union still works.')),
                ('provider', models.CharField(choices=[('xai', 'xAI (Grok)'), ('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI')], default='xai', help_text='Which adapter handles complete() calls. Switch anytime; no code change.', max_length=40)),
                ('model', models.CharField(blank=True, default='', help_text='Model id for the active provider. Examples: grok-4-1-fast-reasoning, grok-4.5, claude-haiku-4-5, gpt-4o-mini. Leave blank to use the built-in default for that provider.', max_length=100)),
                ('xai_api_key', models.CharField(blank=True, default='', help_text='xAI API key (console.x.ai). Leave blank to keep the current value or fall back to XAI_API_KEY env.', max_length=255)),
                ('anthropic_api_key', models.CharField(blank=True, default='', help_text='Anthropic API key. Leave blank to keep current / env fallback.', max_length=255)),
                ('openai_api_key', models.CharField(blank=True, default='', help_text='OpenAI API key. Leave blank to keep current / env fallback.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RAMA configuration',
                'verbose_name_plural': 'RAMA configuration',
            },
        ),
    ]
