# Generated by Django 5.0.12 on 2026-07-17 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rama', '0002_rama_configuration'),
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamaPreferences',
            fields=[
                ('landlord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rama_preferences', serialize=False, to='users.landlordprofile')),
                ('enabled', models.BooleanField(default=False, help_text='When off, the Ask RAMA panel is hidden for this landlord.')),
                ('provider', models.CharField(choices=[('xai', 'xAI (Grok)'), ('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI')], default='xai', max_length=40)),
                ('model', models.CharField(blank=True, default='', help_text='Empty → built-in default for the selected provider.', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RAMA preferences',
                'verbose_name_plural': 'RAMA preferences',
            },
        ),
        migrations.DeleteModel(
            name='RamaConfiguration',
        ),
    ]
