# Generated by Django 5.0.12 on 2026-07-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rama', '0003_per_landlord_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramapreferences',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text="Landlord's provider API key (BYOK). Preferred over platform env keys.", max_length=512),
        ),
    ]
