# Generated by Django 5.0.12 on 2026-07-18 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rama', '0004_byok_api_key'),
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramapreferences',
            name='provider',
            field=models.CharField(choices=[('xai', 'xAI (Grok)'), ('gemini', 'Google Gemini'), ('mistral', 'Mistral AI'), ('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI')], default='xai', max_length=40),
        ),
        migrations.CreateModel(
            name='RamaPendingAction',
            fields=[
                ('conversation_id', models.UUIDField(primary_key=True, serialize=False)),
                ('tool', models.CharField(max_length=100)),
                ('arguments', models.JSONField(default=dict)),
                ('preview', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rama_pending_actions', to='users.landlordprofile')),
            ],
            options={
                'verbose_name': 'RAMA pending action',
                'verbose_name_plural': 'RAMA pending actions',
            },
        ),
    ]
