# Generated by Django 5.0.12 on 2026-07-19 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rama', '0005_alter_ramapreferences_provider_ramapendingaction'),
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramapreferences',
            name='planner_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ramapreferences',
            name='planner_provider',
            field=models.CharField(blank=True, choices=[('xai', 'xAI (Grok)'), ('gemini', 'Google Gemini'), ('mistral', 'Mistral AI'), ('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI')], default='', max_length=40),
        ),
        migrations.CreateModel(
            name='RamaPendingPlan',
            fields=[
                ('conversation_id', models.UUIDField(primary_key=True, serialize=False)),
                ('operation', models.CharField(default='single', max_length=60)),
                ('summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING_CONFIRM', 'Awaiting plan confirmation'), ('AWAITING_STEP_CONFIRM', 'Awaiting step confirmation')], default='PENDING_CONFIRM', max_length=30)),
                ('cursor', models.PositiveIntegerField(default=0)),
                ('blocked', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rama_pending_plans', to='users.landlordprofile')),
            ],
            options={
                'verbose_name': 'RAMA pending plan',
                'verbose_name_plural': 'RAMA pending plans',
            },
        ),
        migrations.CreateModel(
            name='RamaPlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('tool', models.CharField(max_length=100)),
                ('arguments', models.JSONField(default=dict)),
                ('target_label', models.CharField(blank=True, default='', max_length=200)),
                ('item_key', models.CharField(blank=True, default='', max_length=64)),
                ('requires_own_confirm', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='rama.ramapendingplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='RamaPendingAction',
        ),
        migrations.AddConstraint(
            model_name='ramaplanstep',
            constraint=models.UniqueConstraint(fields=('plan', 'order'), name='rama_plan_step_order_unique'),
        ),
    ]
