# Generated by Django 5.0.12 on 2026-07-20 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rama', '0007_role_model_config'),
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamaConstitutionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('body_md', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('origin', models.CharField(choices=[('LANDLORD', 'Landlord'), ('GENERAL_PROPOSAL', 'General (approved proposal)')], default='LANDLORD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rama_constitution_sections', to='users.landlordprofile')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rama.ramaconstitutionsection')),
            ],
            options={
                'ordering': ['key', '-version'],
            },
        ),
        migrations.CreateModel(
            name='RamaConstitutionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('MIN_BALANCE', 'Minimum balance'), ('GRACE_PERIOD', 'Late-payment grace period'), ('LATE_FEE', 'Late fee'), ('VENDOR_PREFERENCE', 'Preferred vendor'), ('AUTO_RECORD_PAYMENT', 'Auto-record payments')], max_length=30)),
                ('params', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rama_constitution_rules', to='users.landlordprofile')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='rama.ramaconstitutionsection')),
            ],
            options={
                'ordering': ['rule_type', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='ramaconstitutionsection',
            constraint=models.UniqueConstraint(fields=('landlord', 'key', 'version'), name='rama_constitution_section_version_unique'),
        ),
    ]
