# Generated by Django 5.0.12 on 2026-07-20 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rama', '0008_ramaconstitutionsection_ramaconstitutionrule_and_more'),
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamaInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=60)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('URGENT', 'Urgent')], default='INFO', max_length=10)),
                ('facts', models.JSONField(default=dict)),
                ('analysis', models.TextField(blank=True, default='')),
                ('proposal_conversation', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKED', 'Acknowledged'), ('ACTIONED', 'Actioned'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('source_event_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rama_insights', to='users.landlordprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['landlord', 'status', '-created_at'], name='rama_ramain_landlor_cf880c_idx')],
            },
        ),
    ]
