# Generated by Django 5.0.12 on 2026-07-21 08:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rama', '0009_ramainsight'),
        ('users', '0007_landlordprofile_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamaUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='rama_uploads/%Y/%m/')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rama_uploads', to='users.landlordprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['landlord', '-created_at'], name='rama_ramaup_landlor_a6f212_idx')],
            },
        ),
    ]
