# Generated by Django 5.0.12 on 2026-07-21 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rama', '0010_ramaupload'),
        ('users', '0007_landlordprofile_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamaCapabilityGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request', models.TextField(help_text='What the landlord wanted, in their words.')),
                ('detail', models.TextField(blank=True, default='', help_text='Why it was blocked / what was missing.')),
                ('prioritised', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed'), ('BUILT', 'Built'), ('DISMISSED', 'Dismissed')], db_index=True, default='NEW', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rama_capability_gaps', to='users.landlordprofile')),
            ],
            options={
                'ordering': ['-prioritised', '-created_at'],
                'indexes': [models.Index(fields=['landlord', 'status', '-created_at'], name='rama_ramaca_landlor_7b92f4_idx')],
            },
        ),
    ]
