# Generated by Django 5.0.12 on 2026-07-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rama', '0011_ramacapabilitygap'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramapreferences',
            name='fsa_api_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='ramapreferences',
            name='general_api_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
