# Generated by Django 5.0.12 on 2026-07-26 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rama', '0013_ramadocument'),
        ('users', '0009_remove_landlordteammember_uniq_team_owner_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramaconstitutionrule',
            name='rule_type',
            field=models.CharField(choices=[('MIN_BALANCE', 'Minimum balance'), ('GRACE_PERIOD', 'Late-payment grace period'), ('LATE_FEE', 'Late fee'), ('VENDOR_PREFERENCE', 'Preferred vendor'), ('AUTO_RECORD_PAYMENT', 'Auto-record payments'), ('AUTONOMY', 'Act without asking (per category)')], max_length=30),
        ),
        migrations.CreateModel(
            name='RamaAutoAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.UUIDField(db_index=True)),
                ('tool', models.CharField(max_length=100)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('target_label', models.CharField(blank=True, default='', max_length=200)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('policy_rule_id', models.IntegerField(blank=True, null=True)),
                ('undo_tool', models.CharField(blank=True, default='', max_length=100)),
                ('undo_arguments', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DONE', 'Done'), ('UNDONE', 'Undone'), ('UNDO_FAILED', 'Undo failed'), ('EXPIRED', 'Too old to undo')], db_index=True, default='DONE', max_length=12)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rama_auto_actions', to='users.landlordprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['landlord', 'status', '-created_at'], name='rama_ramaau_landlor_de15e8_idx')],
            },
        ),
    ]
