# Generated by Django 5.0.12 on 2026-07-26 17:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rama', '0014_autonomy_tier'),
        ('users', '0009_remove_landlordteammember_uniq_team_owner_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamaMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('body', models.TextField()),
                ('scope', models.CharField(choices=[('PORTFOLIO', 'Always relevant'), ('ENTITY', 'Relevant to one property or lease')], default='PORTFOLIO', max_length=12)),
                ('entity_key', models.CharField(blank=True, default='', max_length=120)),
                ('source', models.CharField(choices=[('LANDLORD_EXPLICIT', 'Landlord said to remember it'), ('LANDLORD_IMPLIED', 'Inferred (recorded, not used)')], default='LANDLORD_EXPLICIT', max_length=20)),
                ('origin_conversation', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('FORGOTTEN', 'Forgotten'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=12)),
                ('contains_personal_data', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rama_memories', to='users.landlordprofile')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rama.ramamemory')),
            ],
            options={
                'verbose_name': 'RAMA memory',
                'verbose_name_plural': 'RAMA memories',
                'ordering': ['-pinned', '-updated_at'],
                'indexes': [models.Index(fields=['landlord', 'status', '-updated_at'], name='rama_ramame_landlor_005a2f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ramamemory',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('landlord', 'key'), name='rama_memory_active_key_unique'),
        ),
    ]
