# Generated by Django 5.0.12 on 2026-07-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rama', '0015_rama_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramapreferences',
            name='treasurer_api_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='ramapreferences',
            name='treasurer_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ramapreferences',
            name='treasurer_provider',
            field=models.CharField(blank=True, choices=[('xai', 'xAI (Grok)'), ('gemini', 'Google Gemini'), ('mistral', 'Mistral AI'), ('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI')], default='', max_length=40),
        ),
    ]
