# Generated by Django 5.0.12 on 2026-07-27 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rama', '0016_treasurer_role'),
        ('users', '0009_remove_landlordteammember_uniq_team_owner_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordFinancialProfile',
            fields=[
                ('landlord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='financial_profile', serialize=False, to='users.landlordprofile')),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('consent_scope', models.CharField(default='TAX_ESTIMATES_ONLY', max_length=32)),
                ('occupation', models.CharField(blank=True, default='', max_length=120)),
                ('employment_income_band', models.CharField(blank=True, choices=[('UNDER_50K', 'Under $50,000'), ('B50_100K', '$50,000 – $100,000'), ('B100_150K', '$100,000 – $150,000'), ('B150_250K', '$150,000 – $250,000'), ('OVER_250K', 'Over $250,000'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='', max_length=20)),
                ('other_income_band', models.CharField(blank=True, choices=[('UNDER_50K', 'Under $50,000'), ('B50_100K', '$50,000 – $100,000'), ('B100_150K', '$100,000 – $150,000'), ('B150_250K', '$150,000 – $250,000'), ('OVER_250K', 'Over $250,000'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='', max_length=20)),
                ('filing_situation', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('COUPLE_ONE_INCOME', 'Couple, one income'), ('COUPLE_TWO_INCOMES', 'Couple, two incomes'), ('CORPORATION', 'Held in a corporation'), ('PARTNERSHIP', 'Partnership')], default='', max_length=20)),
                ('tax_province', models.CharField(blank=True, default='', max_length=2)),
                ('self_reported_marginal_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'landlord financial profile',
                'verbose_name_plural': 'landlord financial profiles',
            },
        ),
        migrations.CreateModel(
            name='TaxRateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(max_length=10)),
                ('tax_year', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('PERSONAL_INCOME_BRACKETS', 'Personal income brackets'), ('CCA_CLASSES', 'Capital cost allowance classes'), ('GST_HST_RATE', 'GST/HST rate'), ('CAPITAL_GAINS_INCLUSION', 'Capital gains inclusion')], max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('source_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tax_year', 'jurisdiction'],
            },
        ),
        migrations.AddConstraint(
            model_name='taxratetable',
            constraint=models.UniqueConstraint(fields=('jurisdiction', 'tax_year', 'kind'), name='tax_rate_table_unique_per_year'),
        ),
    ]
