# Generated by Django 5.0.12 on 2026-07-27 21:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0018_moveoutrequest_deposit_settlement_and_more'),
        ('properties', '0015_propertyarea_is_seeded_default'),
        ('rama', '0017_landlordfinancialprofile_taxratetable_and_more'),
        ('users', '0009_remove_landlordteammember_uniq_team_owner_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasurerFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=120)),
                ('subject', models.CharField(max_length=200)),
                ('statement', models.TextField()),
                ('kind', models.CharField(choices=[('LANDLORD_ASSERTED', 'The landlord told us'), ('RESEARCHED', 'Researched, with a source'), ('DERIVED', 'Computed from other facts'), ('ESTIMATE', 'Estimated under stated assumptions'), ('TAX_ASSUMPTION', 'Tax assumption')], max_length=20)),
                ('confidence', models.CharField(choices=[('STATED', 'Stated as fact'), ('RESEARCHED', 'Verified against a source'), ('ESTIMATED', 'Estimated'), ('UNVERIFIED', 'Unverified — excluded from totals')], max_length=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded by a correction'), ('RETRACTED', 'Retracted'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=12)),
                ('direction', models.CharField(choices=[('INCOME', 'Money in'), ('EXPENSE', 'Money out'), ('NEUTRAL', 'Neither (a rate, a value, a count)')], default='NEUTRAL', max_length=8)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('value_unit', models.CharField(default='CAD', max_length=20)),
                ('period', models.CharField(choices=[('ONE_TIME', 'One time'), ('MONTHLY', 'Per month'), ('ANNUAL', 'Per year')], default='ONE_TIME', max_length=12)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=30)),
                ('source_type', models.CharField(default='LANDLORD', max_length=20)),
                ('source_conversation', models.UUIDField(blank=True, null=True)),
                ('asserted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ledger_overlap_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('double_count_risk', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_role', models.CharField(default='landlord', max_length=20)),
                ('contains_personal_data', models.BooleanField(default=False)),
                ('holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='properties.propertyholding')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_facts', to='users.landlordprofile')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leases.lease')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='properties.property')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rama.ramadocument')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rama.treasurerfact')),
            ],
            options={
                'verbose_name': 'treasurer fact',
                'verbose_name_plural': 'treasurer facts',
                'ordering': ['-asserted_at'],
                'indexes': [models.Index(fields=['landlord', 'status', '-asserted_at'], name='rama_treasu_landlor_5fc6a1_idx'), models.Index(fields=['landlord', 'holding', 'effective_from'], name='rama_treasu_landlor_306ace_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='treasurerfact',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('landlord', 'key'), name='treasurer_fact_active_key_unique'),
        ),
    ]
