# Generated by Django 5.0.12 on 2026-07-27 22:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_propertyarea_is_seeded_default'),
        ('rama', '0018_treasurer_facts'),
        ('users', '0009_remove_landlordteammember_uniq_team_owner_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamaDeliberation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=60)),
                ('question', models.TextField()),
                ('trigger', models.CharField(default='landlord_ask', max_length=60)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('AWAITING_INFO', 'Waiting on the landlord'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('SUPERSEDED', 'Superseded by a re-run'), ('ABORTED_BUDGET', 'Stopped at its budget')], db_index=True, default='RUNNING', max_length=16)),
                ('stage_cursor', models.PositiveIntegerField(default=0)),
                ('calls_used', models.PositiveIntegerField(default=0)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='properties.propertyholding')),
                ('insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rama.ramainsight')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rama_deliberations', to='users.landlordprofile')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rama.ramadeliberation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RamaDeliberationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('stage', models.CharField(max_length=20)),
                ('option_key', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('RETRIED', 'Retried'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('conversation_id', models.UUIDField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('input_artifact', models.JSONField(blank=True, default=dict)),
                ('output_artifact', models.JSONField(blank=True, default=dict)),
                ('raw_reply', models.TextField(blank=True, default='')),
                ('violations', models.JSONField(blank=True, default=list)),
                ('retries', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deliberation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='rama.ramadeliberation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RamaOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogue_key', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('GATHERED', 'Facts gathered'), ('SCORED', 'Scored'), ('BLOCKED', 'Blocked'), ('EXCLUDED', 'Excluded')], default='CANDIDATE', max_length=10)),
                ('excluded_reason', models.CharField(blank=True, default='', max_length=200)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('deliberation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='rama.ramadeliberation')),
            ],
            options={
                'ordering': ['rank', 'catalogue_key'],
            },
        ),
        migrations.AddIndex(
            model_name='ramadeliberation',
            index=models.Index(fields=['landlord', 'status', '-created_at'], name='rama_ramade_landlor_0b12b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='ramadeliberationstage',
            constraint=models.UniqueConstraint(fields=('deliberation', 'order'), name='rama_stage_unique_order'),
        ),
        migrations.AddConstraint(
            model_name='ramaoption',
            constraint=models.UniqueConstraint(fields=('deliberation', 'catalogue_key'), name='rama_option_unique_per_deliberation'),
        ),
    ]
