# Generated by Django 5.0.12 on 2026-07-28 04:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rama', '0019_deliberation'),
        ('users', '0009_remove_landlordteammember_uniq_team_owner_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasurerSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(db_index=True, max_length=60)),
                ('query', models.CharField(blank=True, default='', max_length=300)),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('domain', models.CharField(db_index=True, max_length=120)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('fetched_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('http_status', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('FRESH', 'Fresh'), ('STALE', 'Past its expiry'), ('DEAD', 'Could not be fetched'), ('BLOCKED', 'Refused before fetching')], db_index=True, default='FRESH', max_length=8)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_sources', to='users.landlordprofile')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['landlord', 'topic', '-fetched_at'], name='rama_treasu_landlor_65f86b_idx')],
            },
        ),
    ]
