# Generated by Django 5.0.12 on 2026-07-28 05:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rama', '0020_treasurer_sources'),
        ('users', '0009_remove_landlordteammember_uniq_team_owner_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasurerRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fact_key', models.SlugField(blank=True, default='', max_length=120)),
                ('question', models.TextField()),
                ('why_it_matters', models.TextField(blank=True, default='')),
                ('expected_unit', models.CharField(blank=True, default='', max_length=20)),
                ('expected_period', models.CharField(blank=True, default='', max_length=12)),
                ('blocking', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RELAYED', 'Passed to the landlord'), ('ANSWERED', 'Answered'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], db_index=True, default='OPEN', max_length=10)),
                ('relayed_at', models.DateTimeField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True, default='')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deliberation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='rama.ramadeliberation')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_requests', to='users.landlordprofile')),
                ('resulting_fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rama.treasurerfact')),
            ],
            options={
                'ordering': ['-blocking', 'created_at'],
                'indexes': [models.Index(fields=['landlord', 'status', 'created_at'], name='rama_treasu_landlor_36a646_idx')],
            },
        ),
    ]
