# Generated by Django 5.0.12 on 2026-07-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rama', '0021_treasurer_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramadocument',
            name='kind',
            field=models.CharField(choices=[('EXPENSE', 'Expense / payable'), ('NOTICE', 'Notice'), ('MORTGAGE', 'Mortgage / financing'), ('INSURANCE', 'Insurance'), ('LEASE', 'Lease / tenancy'), ('TAX', 'Tax record'), ('MAINTENANCE', 'Maintenance'), ('BANK_STATEMENT', 'Bank / card statement'), ('OTHER', 'Other document')], default='OTHER', max_length=20),
        ),
    ]
