# Generated by Django 5.0.12 on 2026-07-30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rama", "0022_alter_ramadocument_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="RamaAttachmentBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("conversation_id", models.UUIDField(db_index=True)),
                ("message_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("SEALED", "Sealed"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sealed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rama_attachment_batches",
                        to="users.landlordprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["landlord", "conversation_id", "-created_at"],
                        name="rama_attachment_batch_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RamaTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("conversation_id", models.UUIDField(db_index=True)),
                ("capability_key", models.CharField(db_index=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("NEEDS_INPUT", "Needs input"),
                            ("READY", "Ready"),
                            ("AWAITING_CONFIRMATION", "Awaiting confirmation"),
                            ("EXECUTING", "Executing"),
                            ("VERIFIED", "Verified"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="RECEIVED",
                        max_length=30,
                    ),
                ),
                ("input", models.JSONField(blank=True, default=dict)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("outcome", models.JSONField(blank=True, default=dict)),
                ("idempotency_key", models.CharField(blank=True, default="", max_length=160)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rama_tasks",
                        to="users.landlordprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["landlord", "conversation_id", "-created_at"],
                        name="rama_task_conversation_idx",
                    ),
                    models.Index(
                        fields=["landlord", "idempotency_key"],
                        name="rama_task_idempotency_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RamaAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original", models.FileField(upload_to="rama_attachments/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, default="", max_length=160)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("PROPERTY_PHOTO", "Property photo"),
                            ("DOCUMENT", "Document"),
                        ],
                        default="UNKNOWN",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STAGED", "Staged"),
                            ("CLASSIFIED", "Classified"),
                            ("APPLIED", "Applied"),
                            ("REJECTED", "Rejected"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="STAGED",
                        max_length=20,
                    ),
                ),
                ("target_type", models.CharField(blank=True, default="", max_length=80)),
                ("target_id", models.CharField(blank=True, default="", max_length=100)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="rama.ramaattachmentbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "sequence"),
                        name="rama_attachment_batch_sequence_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RamaActionReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("capability_key", models.CharField(db_index=True, max_length=120)),
                ("idempotency_key", models.CharField(max_length=160)),
                ("inputs", models.JSONField(default=dict)),
                ("effects", models.JSONField(default=dict)),
                ("entity_refs", models.JSONField(blank=True, default=list)),
                ("verification", models.JSONField(default=dict)),
                ("links", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rama_action_receipts",
                        to="users.landlordprofile",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="rama.ramatask",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["landlord", "capability_key", "-created_at"],
                        name="rama_receipt_capability_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("landlord", "idempotency_key"),
                        name="rama_receipt_landlord_idempotency_unique",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="ramapendingplan",
            name="task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_plan",
                to="rama.ramatask",
            ),
        ),
        migrations.AddField(
            model_name="ramaplanstep",
            name="capability_key",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="ramaplanstep",
            name="receipt",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plan_step",
                to="rama.ramaactionreceipt",
            ),
        ),
    ]
