# Generated by Django 5.0.12 on 2026-07-31 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_holdingfinancials_holdingvaluation_holdingmortgage_and_more'),
        ('properties', '0016_property_furnishing_status'),
        ('rama', '0023_command_engine_and_attachment_batches'),
        ('users', '0009_remove_landlordteammember_uniq_team_owner_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramadocumentevent',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rama.ramadocument'),
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='users.landlordprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ramadocument',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Filing labels (tax-2026, insurance, hvac, …).', related_name='documents', to='rama.documenttag'),
        ),
        migrations.AddIndex(
            model_name='ramadocument',
            index=models.Index(fields=['landlord', 'kind', '-document_date'], name='rama_doc_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttag',
            constraint=models.UniqueConstraint(fields=('landlord', 'slug'), name='rama_documenttag_landlord_slug_unique'),
        ),
    ]
