# Generated by Django 5.0.12 on 2026-07-10 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0012_lease_custom_tenant_notice_months_moveoutrequest'),
        ('maintenance', '0001_initial'),
        ('properties', '0008_propertyarea_shared_with_landlord'),
        ('users', '0005_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('VIEWING', 'Viewing / Showing'), ('CONTRACTOR', 'Contractor / Maintenance Visit'), ('OTHER', 'Other')], default='VIEWING', max_length=15)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=12)),
                ('starts_at', models.DateTimeField(verbose_name='Starts At')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Ends At')),
                ('contact_name', models.CharField(blank=True, help_text='Prospective tenant, contractor/company, etc.', max_length=200, verbose_name="Who's Coming")),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Contact Phone')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.landlordprofile')),
                ('lease', models.ForeignKey(blank=True, help_text='Current tenancy affected (tenants on it can see the appointment — this is their entry notice).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='leases.lease')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='properties.property')),
                ('work_order', models.ForeignKey(blank=True, help_text='For contractor visits: the work order being serviced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='maintenance.workorder')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['starts_at'],
            },
        ),
    ]
