# Generated by Django 5.0.12 on 2026-07-11 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('leases', '0012_lease_custom_tenant_notice_months_moveoutrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='For public viewing requests: how to reach the requester.', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='lease',
            field=models.ForeignKey(blank=True, help_text='Current tenancy affected (tenants on it see the appointment — their entry notice).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='leases.lease'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested (awaiting confirmation)'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=12),
        ),
    ]
