# Generated by Django 5.0.12 on 2026-07-12 01:08

import rentium.core.phone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_contact_email_alter_appointment_lease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='contact_phone',
            field=rentium.core.phone.PhoneField(blank=True, default='', max_length=20, verbose_name='Contact Phone'),
        ),
    ]
