# Generated by Django 5.0.12 on 2026-07-20 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_public_token'),
        ('properties', '0010_propertyholding_property_holding'),
        ('users', '0007_landlordprofile_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='users.landlordprofile')),
                ('property', models.ForeignKey(blank=True, help_text="Set to override this landlord's default hours for one property.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='properties.property')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'indexes': [models.Index(fields=['landlord', 'property', 'weekday'], name='appointment_landlor_ef1eb4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='availabilitywindow',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='availability_window_end_after_start'),
        ),
    ]
