# Generated by Django 5.0.12 on 2026-07-20 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_availabilitywindow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tenant_consent',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'No current tenant'), ('PENDING', 'Asked — awaiting the tenant'), ('OK', 'Tenant is fine with it'), ('OBJECTED', 'Tenant raised a concern')], default='NOT_APPLICABLE', max_length=15),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tenant_consent_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_class',
            field=models.CharField(choices=[('UNSET', 'Not classified'), ('IN_HOURS', 'Within preferred hours'), ('OUT_OF_HOURS', 'Outside preferred hours')], default='UNSET', max_length=15),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='kind',
            field=models.CharField(choices=[('VIEWING', 'Viewing / Showing'), ('INSPECTION', 'Move-in / Move-out Inspection'), ('CONTRACTOR', 'Contractor / Maintenance Visit'), ('OTHER', 'Other')], default='VIEWING', max_length=15),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested (awaiting landlord)'), ('AWAITING_REQUESTER', "Awaiting requester's reply (landlord proposed a time)"), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.CreateModel(
            name='AppointmentProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_by', models.CharField(choices=[('LANDLORD', 'Landlord'), ('REQUESTER', 'Prospective tenant'), ('TENANT', 'Current tenant')], max_length=10)),
                ('starts_at', models.DateTimeField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='appointments.appointment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
