# Generated by Django 5.0.12 on 2026-07-20 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_tenant_consent_and_more'),
        ('leases', '0013_lease_house_rules_lease_occupants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='inspection',
            field=models.ForeignKey(blank=True, help_text='For move-in / move-out inspection walkthroughs: the condition report this visit is scheduling.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='leases.conditioninspection'),
        ),
    ]
