# Generated by Django 5.0.12 on 2026-07-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitywindow',
            name='specific_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
