# Generated by Django 5.0.12 on 2026-07-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_availabilitywindow_specific_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prospect_link_first_opened_at',
            field=models.DateTimeField(blank=True, help_text='First time the prospect opened their status/invite link.', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prospect_link_last_opened_at',
            field=models.DateTimeField(blank=True, help_text='Most recent time the prospect opened their status/invite link.', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prospect_link_open_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times the status/invite page was loaded.'),
        ),
    ]
